"""Generate map documentation and CSVs from a ROM definition file (``analysis/defs/<rom>.yaml``).

The YAML file is the single source of truth (CLAUDE.md). This module reads the
table bytes from the ROM and writes:

* ``analysis/<rom>/maps.md``: every map with its axes, values, evidence and confidence;
* ``analysis/<rom>/maps/<id>.csv``: one CSV per map (axis values as headers);
* ``analysis/<rom>/<rom>.xdf``: a TunerPro RT definition for editing the raw ROM image.
  Cells show raw values unless the YAML gives ``cell.equation`` (TunerPro syntax in X).
  An edited ROM must have its checksum re-balanced with ``pcmre.checksum``.

A TunerStudio INI needs a live comms protocol, so it waits for P7 (the in-car board).

    PYTHONPATH=analysis uv run python -m pcmre.defs            # check
    PYTHONPATH=analysis uv run python -m pcmre.defs --write    # regenerate
"""

from __future__ import annotations

import argparse
import hashlib
import io
import sys
from dataclasses import dataclass, field
from pathlib import Path
from xml.sax.saxutils import escape, quoteattr

import yaml

ROOT = Path(__file__).resolve().parents[2]


@dataclass
class Generated:
    markdown: str
    csvs: dict[str, str]  # map id -> CSV text
    xdf: str = field(default="")


def load(rom_name: str) -> tuple[dict, bytes]:
    spec = yaml.safe_load((ROOT / "analysis/defs" / f"{rom_name}.yaml").read_text())
    rom = (ROOT / spec["file"]).read_bytes()
    if hashlib.sha256(rom).hexdigest() != spec["sha256"]:
        raise ValueError(f"{spec['file']} does not match the sha256 in the definition file")
    return spec, rom


def map_bytes(spec: dict, rom: bytes, m: dict) -> bytes:
    size = m["rows"] * m["cols"] if m["kind"] == "3d" else m["length"]
    off = m["addr"] - spec["base"]
    if off < 0 or off + size > len(rom):
        raise ValueError(f"{m['id']}: ${m['addr']:04X}+{size} is outside the ROM")
    return rom[off : off + size]


def axis_1d(m: dict) -> list[int]:
    ax = m["axis"]
    if "raw" in ax:
        return list(ax["raw"])
    return [i << ax["shift"] for i in range(m["length"])]


def _fmt_axis(values) -> list[str]:
    return [str(v) for v in values]


def generate(spec: dict, rom: bytes) -> Generated:
    out = io.StringIO()
    csvs: dict[str, str] = {}
    w = out.write
    w(f"# Map definitions: {spec['rom']}\n\n")
    w(f"Generated by `analysis/pcmre/defs.py` from [`../defs/{spec['rom']}.yaml`](../defs/{spec['rom']}.yaml). ")
    w("**Do not edit by hand.** A test fails if this file or the CSVs are stale.\n\n")
    w(f"ROM: `{spec['file']}` (sha256 `{spec['sha256'][:12]}…`), base `${spec['base']:04X}`.\n\n")

    w("## Variables\n\n| Variable | RAM | Unit | To physical | Evidence | Confidence |\n|---|---|---|---|---|---|\n")
    for name, v in spec.get("variables", {}).items():
        w(
            f"| `{name}` | `${v['addr']:02X}` | {v['unit']} | {v['to_physical']} "
            f"| {v['evidence']} | {v['confidence']} |\n"
        )
    w("\n## Index\n\n| Id | Address | Kind | Size | Name | Confidence |\n|---|---|---|---|---|---|\n")
    for m in spec["maps"]:
        size = f"{m['rows']}×{m['cols']}" if m["kind"] == "3d" else str(m["length"])
        w(
            f"| [`{m['id']}`](#{m['id']}) | `${m['addr']:04X}` | {m['kind']} | {size} "
            f"| {m['name']} | {m['confidence']} |\n"
        )
    w("\n")

    for m in spec["maps"]:
        data = map_bytes(spec, rom, m)
        w(f"## {m['id']}\n\n**{m['name']}** at `${m['addr']:04X}`")
        if "entry" in m:
            w(f", read through helper entry `${m['entry']:04X}`")
        w(".\n\n")
        w(f"- Cells: {m['cell']['unit']}" + (f". {m['cell']['note']}" if m["cell"].get("note") else "") + "\n")
        if m.get("claims"):
            w(f"- Ross claims: {', '.join(m['claims'])}\n")
        w(f"- Evidence: {m['evidence']}\n- Confidence: {m['confidence']}\n")
        csv = io.StringIO()
        if m["kind"] == "3d":
            ra, ca = m["row_axis"], m["col_axis"]
            w(f"- Rows: `{ra['var']}` raw {', '.join(f'${v:04X}' for v in ra['raw'])}. {ra.get('note', '')}\n")
            phys = ca.get("physical")
            w(f"- Columns: `{ca['var']}` raw {', '.join(map(str, ca['raw']))}")
            w(f" = {', '.join(map(str, phys))} {ca.get('unit', '')}\n\n" if phys else "\n\n")
            head = phys or ca["raw"]
            w("| Load row \\ col | " + " | ".join(map(str, head)) + " |\n")
            w("|---" * (len(head) + 1) + "|\n")
            csv.write("row," + ",".join(map(str, head)) + "\n")
            for r in range(m["rows"]):
                row = data[r * m["cols"] : (r + 1) * m["cols"]]
                label = f"${ra['raw'][r]:04X}"
                w(f"| {label} | " + " | ".join(map(str, row)) + " |\n")
                csv.write(f"{label}," + ",".join(map(str, row)) + "\n")
        else:
            ax = m["axis"]
            pts = axis_1d(m)
            w(f"- Axis: `{ax['var']}` ({ax['unit']}), raw points every {1 << ax.get('shift', 0)}\n\n")
            w(f"| {ax['var']} | " + " | ".join(_fmt_axis(pts)) + " |\n" + "|---" * (len(pts) + 1) + "|\n")
            w("| value | " + " | ".join(map(str, data)) + " |\n")
            csv.write(f"{ax['var']},value\n")
            for p, v in zip(pts, data, strict=True):
                csv.write(f"{p},{v}\n")
        w("\n")
        csvs[m["id"]] = csv.getvalue()
    return Generated(out.getvalue(), csvs, xdf(spec))


def _axis_xml(axis_id: str, labels: list, units: str) -> str:
    lines = [
        f'    <XDFAXIS id="{axis_id}" uniqueid="0x0">',
        '      <EMBEDDEDDATA mmedelementsizebits="8" mmedmajorstridebits="-32" mmedminorstridebits="0" />',
        f"      <units>{escape(units)}</units>",
        f"      <indexcount>{len(labels)}</indexcount>",
        '      <embedinfo type="1" />',
        "      <datatype>0</datatype>",
        "      <unittype>0</unittype>",
        '      <DALINK index="0" />',
    ]
    lines += [f'      <LABEL index="{i}" value={quoteattr(str(v))} />' for i, v in enumerate(labels)]
    lines += ['      <MATH equation="X">', '        <VAR id="X" />', "      </MATH>", "    </XDFAXIS>"]
    return "\n".join(lines)


def xdf(spec: dict) -> str:
    """TunerPro RT XDF (format 1.70) for the raw ROM image; addresses are file offsets."""
    cats = sorted({m.get("category", "Tables") for m in spec["maps"]})
    size = 0x10000 - spec["base"]
    out = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        f"<!-- Generated by analysis/pcmre/defs.py from analysis/defs/{spec['rom']}.yaml. Do not edit by hand. -->",
        '<XDFFORMAT version="1.70">',
        "  <XDFHEADER>",
        "    <flags>0x1</flags>",
        f"    <deftitle>{escape(spec['rom'])} ({escape(spec['file'])})</deftitle>",
        "    <description>"
        + escape(
            f"Generated from analysis/defs/{spec['rom']}.yaml. ROM sha256 {spec['sha256']}. "
            "Confidence and evidence for every table are in the YAML and maps.md. "
            "After editing, re-balance the checksum: python -m pcmre.checksum FILE --fix"
        )
        + "</description>",
        '    <BASEOFFSET offset="0" subtract="0" />',
        '    <DEFAULTS datasizeinbits="8" sigdigits="2" outputtype="1" signed="0" lsbfirst="0" float="0" />',
        f'    <REGION type="0xFFFFFFFF" startaddress="0x0" size="0x{size:X}" regionflags="0x0" '
        f'name="Binary File" desc="ROM ${spec["base"]:04X}-$FFFF" />',
    ]
    out += [f'    <CATEGORY index="0x{i:X}" name={quoteattr(c)} />' for i, c in enumerate(cats)]
    out.append("  </XDFHEADER>")
    for n, m in enumerate(spec["maps"], start=1):
        off = m["addr"] - spec["base"]
        cell = m["cell"]
        eq = cell.get("equation", "X")
        unit = cell.get("eq_unit", cell["unit"]) if "equation" in cell else cell["unit"]
        if m["kind"] == "3d":
            rows, cols = m["rows"], m["cols"]
            xl = m["col_axis"].get("physical") or m["col_axis"]["raw"]
            yl = [f"${v:04X}" for v in m["row_axis"]["raw"]]
            xu, yu = m["col_axis"].get("unit", m["col_axis"]["var"]), m["row_axis"]["var"]
        else:
            rows, cols = 1, m["length"]
            xl, yl = axis_1d(m), [""]
            xu, yu = m["axis"]["var"], ""
        desc = f"{m['name']}. Evidence: {m['evidence']}. Confidence: {m['confidence']}."
        if cell.get("note"):
            desc += f" {cell['note']}"
        out += [
            f'  <XDFTABLE uniqueid="0x{n:X}" flags="0x0">',
            f"    <title>{escape(m['id'] + ': ' + m['name'])}</title>",
            f"    <description>{escape(desc)}</description>",
            f'    <CATEGORYMEM index="0" category="{cats.index(m.get("category", "Tables")) + 1}" />',
            _axis_xml("x", xl, str(xu)),
            _axis_xml("y", yl, str(yu)),
            '    <XDFAXIS id="z">',
            f'      <EMBEDDEDDATA mmedaddress="0x{off:X}" mmedelementsizebits="8" mmedrowcount="{rows}" '
            f'mmedcolcount="{cols}" mmedmajorstridebits="0" mmedminorstridebits="0" />',
            f"      <units>{escape(str(unit))}</units>",
            "      <decimalpl>1</decimalpl>" if eq != "X" else "      <decimalpl>0</decimalpl>",
            "      <outputtype>1</outputtype>",
            f"      <MATH equation={quoteattr(eq)}>",
            '        <VAR id="X" />',
            "      </MATH>",
            "    </XDFAXIS>",
            "  </XDFTABLE>",
        ]
    out.append("</XDFFORMAT>")
    return "\n".join(out) + "\n"


def write(rom_name: str, gen: Generated) -> None:
    base = ROOT / "analysis" / rom_name
    (base / "maps").mkdir(parents=True, exist_ok=True)
    (base / "maps.md").write_text(gen.markdown)
    for mid, text in gen.csvs.items():
        (base / "maps" / f"{mid}.csv").write_text(text)
    (base / f"{rom_name}.xdf").write_text(gen.xdf)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("rom", nargs="?", default="bluetop")
    ap.add_argument("--write", action="store_true")
    a = ap.parse_args()
    spec, rom = load(a.rom)
    gen = generate(spec, rom)
    print(f"{a.rom}: {len(spec['maps'])} maps")
    if a.write:
        write(a.rom, gen)
        print(f"wrote analysis/{a.rom}/maps.md, {len(gen.csvs)} CSVs and {a.rom}.xdf")
    return 0


if __name__ == "__main__":
    sys.exit(main())
