"""Generate map documentation and CSVs from a ROM definition file (``analysis/defs/<rom>.yaml``).

The YAML file is the single source of truth (CLAUDE.md). This module reads the
table bytes from the ROM and writes:

* ``analysis/<rom>/maps.md``: every map with its axes, values, evidence and confidence;
* ``analysis/<rom>/maps/<id>.csv``: one CSV per map (axis values as headers).

XDF and TunerStudio INI outputs come later; they are generated from the same YAML.

    PYTHONPATH=analysis uv run python -m pcmre.defs            # check
    PYTHONPATH=analysis uv run python -m pcmre.defs --write    # regenerate
"""

from __future__ import annotations

import argparse
import hashlib
import io
import sys
from dataclasses import dataclass
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]


@dataclass
class Generated:
    markdown: str
    csvs: dict[str, str]  # map id -> CSV text


def load(rom_name: str) -> tuple[dict, bytes]:
    spec = yaml.safe_load((ROOT / "analysis/defs" / f"{rom_name}.yaml").read_text())
    rom = (ROOT / spec["file"]).read_bytes()
    if hashlib.sha256(rom).hexdigest() != spec["sha256"]:
        raise ValueError(f"{spec['file']} does not match the sha256 in the definition file")
    return spec, rom


def map_bytes(spec: dict, rom: bytes, m: dict) -> bytes:
    size = m["rows"] * m["cols"] if m["kind"] == "3d" else m["length"]
    off = m["addr"] - spec["base"]
    if off < 0 or off + size > len(rom):
        raise ValueError(f"{m['id']}: ${m['addr']:04X}+{size} is outside the ROM")
    return rom[off : off + size]


def axis_1d(m: dict) -> list[int]:
    ax = m["axis"]
    if "raw" in ax:
        return list(ax["raw"])
    return [i << ax["shift"] for i in range(m["length"])]


def _fmt_axis(values) -> list[str]:
    return [str(v) for v in values]


def generate(spec: dict, rom: bytes) -> Generated:
    out = io.StringIO()
    csvs: dict[str, str] = {}
    w = out.write
    w(f"# Map definitions: {spec['rom']}\n\n")
    w(f"Generated by `analysis/pcmre/defs.py` from [`../defs/{spec['rom']}.yaml`](../defs/{spec['rom']}.yaml). ")
    w("**Do not edit by hand.** A test fails if this file or the CSVs are stale.\n\n")
    w(f"ROM: `{spec['file']}` (sha256 `{spec['sha256'][:12]}…`), base `${spec['base']:04X}`.\n\n")

    w("## Variables\n\n| Variable | RAM | Unit | To physical | Evidence | Confidence |\n|---|---|---|---|---|---|\n")
    for name, v in spec.get("variables", {}).items():
        w(
            f"| `{name}` | `${v['addr']:02X}` | {v['unit']} | {v['to_physical']} "
            f"| {v['evidence']} | {v['confidence']} |\n"
        )
    w("\n## Index\n\n| Id | Address | Kind | Size | Name | Confidence |\n|---|---|---|---|---|---|\n")
    for m in spec["maps"]:
        size = f"{m['rows']}×{m['cols']}" if m["kind"] == "3d" else str(m["length"])
        w(
            f"| [`{m['id']}`](#{m['id']}) | `${m['addr']:04X}` | {m['kind']} | {size} "
            f"| {m['name']} | {m['confidence']} |\n"
        )
    w("\n")

    for m in spec["maps"]:
        data = map_bytes(spec, rom, m)
        w(f"## {m['id']}\n\n**{m['name']}** at `${m['addr']:04X}`")
        if "entry" in m:
            w(f", read through helper entry `${m['entry']:04X}`")
        w(".\n\n")
        w(f"- Cells: {m['cell']['unit']}" + (f". {m['cell']['note']}" if m["cell"].get("note") else "") + "\n")
        if m.get("claims"):
            w(f"- Ross claims: {', '.join(m['claims'])}\n")
        w(f"- Evidence: {m['evidence']}\n- Confidence: {m['confidence']}\n")
        csv = io.StringIO()
        if m["kind"] == "3d":
            ra, ca = m["row_axis"], m["col_axis"]
            w(f"- Rows: `{ra['var']}` raw {', '.join(f'${v:04X}' for v in ra['raw'])}. {ra.get('note', '')}\n")
            phys = ca.get("physical")
            w(f"- Columns: `{ca['var']}` raw {', '.join(map(str, ca['raw']))}")
            w(f" = {', '.join(map(str, phys))} {ca.get('unit', '')}\n\n" if phys else "\n\n")
            head = phys or ca["raw"]
            w("| Load row \\ col | " + " | ".join(map(str, head)) + " |\n")
            w("|---" * (len(head) + 1) + "|\n")
            csv.write("row," + ",".join(map(str, head)) + "\n")
            for r in range(m["rows"]):
                row = data[r * m["cols"] : (r + 1) * m["cols"]]
                label = f"${ra['raw'][r]:04X}"
                w(f"| {label} | " + " | ".join(map(str, row)) + " |\n")
                csv.write(f"{label}," + ",".join(map(str, row)) + "\n")
        else:
            ax = m["axis"]
            pts = axis_1d(m)
            w(f"- Axis: `{ax['var']}` ({ax['unit']}), raw points every {1 << ax.get('shift', 0)}\n\n")
            w(f"| {ax['var']} | " + " | ".join(_fmt_axis(pts)) + " |\n" + "|---" * (len(pts) + 1) + "|\n")
            w("| value | " + " | ".join(map(str, data)) + " |\n")
            csv.write(f"{ax['var']},value\n")
            for p, v in zip(pts, data, strict=True):
                csv.write(f"{p},{v}\n")
        w("\n")
        csvs[m["id"]] = csv.getvalue()
    return Generated(out.getvalue(), csvs)


def write(rom_name: str, gen: Generated) -> None:
    base = ROOT / "analysis" / rom_name
    (base / "maps").mkdir(parents=True, exist_ok=True)
    (base / "maps.md").write_text(gen.markdown)
    for mid, text in gen.csvs.items():
        (base / "maps" / f"{mid}.csv").write_text(text)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("rom", nargs="?", default="bluetop")
    ap.add_argument("--write", action="store_true")
    a = ap.parse_args()
    spec, rom = load(a.rom)
    gen = generate(spec, rom)
    print(f"{a.rom}: {len(spec['maps'])} maps")
    if a.write:
        write(a.rom, gen)
        print(f"wrote analysis/{a.rom}/maps.md and {len(gen.csvs)} CSVs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
