"""Readable ignition table: the Bluetop base map in degrees, with load as a percentage.

    PYTHONPATH=analysis uv run python -m pcmre.readable          # print
    PYTHONPATH=analysis uv run python -m pcmre.readable --write  # docs/bluetop/ignition_table.md + CSV

Every number comes from the ROM's own arithmetic, already verified in the simulator:

- degrees: the ROM's advance sum and µs conversion [ROM:$F8CD-$F90D]
  (tests/test_sim.py::advance_from_rom_formula), warm (ThW_tADV = 28), off idle,
  PWRr trim 0;
- T-VIS: +8 raw while TVIScounter >= 0, the state above 4350 rpm [ROM:$FC47-$FC6D, $F89F];
- full-load line: the measured airflow delay is clamped to SE056Maxtime =
  se056_max(FullRPM) * 8 + $800 µs, FullRPM = rpm * 0.32 [ROM:$F582-$F58E, $F1DA].
"""

from __future__ import annotations

import argparse
import sys

from .defs import ROOT, load
from .tables import lookup_1d

DOC = ROOT / "docs/bluetop/ignition_table.md"
CSV = ROOT / "analysis/bluetop/readable/ign_base_degrees.csv"
FULL_SCALE = 0x0C00  # top row of the map, µs of airflow delay = 100 %
THW_WARM = 28
TVIS_RPM = 4350  # rises above 4350, falls back below 3950 [ROM:$FC47-$FC55]
LEAD_US = 256


def degrees(cell: int, rpm: int, tvis: bool, lead: bool = False) -> float:
    """Spark angle BTDC for a map cell [ROM:$F8CD-$F90D]; ``lead`` adds the ROM's fixed 256 µs."""
    delta_ne = round(30_000_000 / rpm)
    total = min(max(cell + (8 if tvis else 0) + THW_WARM, 0x1F), 0xB8)
    b = total - 0x1C
    adv_us = ((delta_ne * (b + 1)) >> 9) - (delta_ne >> 4) + (LEAD_US if lead else 0)
    return 10 + adv_us * 180 / delta_ne


def lead_degrees(rpm: int) -> float:
    return LEAD_US * 1e-6 * rpm / 60 * 360


def full_load_us(rom: bytes, spec: dict, rpm: int) -> int:
    """SE056Maxtime at this rpm: the most airflow delay the ROM accepts."""
    m = next(m for m in spec["maps"] if m["id"] == "se056_max")
    t = rom[m["addr"] - spec["base"] : m["addr"] - spec["base"] + m["length"] + 1]
    full = min(round(rpm * 0.32), 0x09FF)
    return lookup_1d(t, full >> 8, full & 0xFF, entry=m["entry"]) * 8 + 0x800


def build() -> tuple[str, str]:
    spec, rom = load("bluetop")
    m = next(m for m in spec["maps"] if m["id"] == "ign_base")
    rows, cols = m["rows"], m["cols"]
    rpms = m["col_axis"]["physical"]
    loads = m["row_axis"]["raw"]
    cells = rom[m["addr"] - spec["base"] : m["addr"] - spec["base"] + rows * cols]
    pct = [round(v * 100 / FULL_SCALE) for v in loads]
    ceiling = [full_load_us(rom, spec, r) for r in rpms]
    tvis = [r > TVIS_RPM for r in rpms]

    csv = ["load_pct,load_us," + ",".join(str(r) for r in rpms)]
    md = [
        "# Bluetop ignition map in degrees",
        "",
        "Generated by `python -m pcmre.readable --write` "
        "([`../../analysis/pcmre/readable.py`](../../analysis/pcmre/readable.py)). Do not edit.",
        "",
        "The base ignition map (`ign_base`, `$FF40` in 0642, `$FF5A` in 2860; identical in both) with:",
        "- **load as a percentage**, and",
        "- **each cell converted to degrees BTDC** with the ROM's own arithmetic.",
        "",
        "Load is what the ECU calls `Load`: the airflow-meter pulse delay in µs, after the air-temperature correction.",
        "On this airflow-meter ECU that pulse is the base fuel pulse, so it tracks **air per intake stroke** "
        "(LIKELY; grams per stroke are unknown until the SE056 is measured).",
        f"Here **100 % = {FULL_SCALE} µs, the map's top row**.",
        "",
        "## Degrees BTDC (warm engine, throttle open)",
        "",
        "| Load \\ rpm | " + " | ".join(str(r) for r in rpms) + " |",
        "|---|" + "---|" * cols,
    ]
    for r in range(rows - 1, -1, -1):  # high load at the top, like a tuning screen
        vals = []
        for c in range(cols):
            d = degrees(cells[r * cols + c], rpms[c], tvis[c])
            reach = loads[r] <= ceiling[c]
            vals.append(f"{d:.1f}" if reach else f"({d:.1f})")
        md.append(f"| **{pct[r]} %** | " + " | ".join(vals) + " |")
        csv.append(
            f"{pct[r]},{loads[r]},"
            + ",".join(f"{degrees(cells[r * cols + c], rpms[c], tvis[c]):.2f}" for c in range(cols))
        )
    md += [
        "| *full-load line* | " + " | ".join(f"{round(x * 100 / FULL_SCALE)} %" for x in ceiling) + " |",
        "| *256 µs lead* | " + " | ".join(f"+{lead_degrees(r):.1f}" for r in rpms) + " |",
        "",
        "## How to read it",
        "",
        "- **Full-load line:** the ECU clamps measured airflow at each rpm (`se056_max`), so load cannot exceed "
        "this percentage there. Cells in **(brackets)** lie above the line. They are only reached as "
        "interpolation targets, so they shape the timing just below full load but are never used as they stand. "
        "The line assumes a neutral air-temperature correction; cold, dense air raises measured load by up to "
        "about 11 % (`tha_corr`).",
        "- **Rows in between:** the ECU interpolates in both rpm and load.",
        f"- **T-VIS:** the columns above {TVIS_RPM} rpm include **+2.8°** (+8 raw). The ROM adds it once "
        "T-VIS has opened [ROM:$F89F], after a short counter delay. The changeover has hysteresis: "
        "it opens rising past 4350 rpm and closes falling below 3950 rpm. So the 4000 rpm column gets the "
        "+2.8° only when coming down from above 4350.",
        "- **256 µs lead:** the ROM fires every spark 256 µs earlier than the map angle "
        "[ROM:$F900]; the row shows what that is worth at each rpm. If the lead only cancels a hardware delay "
        "(igniter, NE filtering), the table above is the real crank angle. If not, add the lead row. This is open "
        "question Q3, settled by the P8 bench capture.",
        "",
        "## What the table does not include",
        "",
        "- **Idle (throttle closed):** this map is not used. The ECU uses a fixed 16.3° plus idle-speed "
        "corrections ([`simulation.md`](simulation.md)).",
        "- **Cold engine:** `thw_FF0A` adds extra advance below operating temperature, and `overheat_adv` "
        "retards above 218 °F.",
        "- **`pwr_ign_trim`:** a selectable trim of 0 to a few degrees (the PWRr input), taken here as 0.",
        "- **Limits:** the total is clamped to about 10° to 64°.",
        "",
        "Confidence: the conversion is CONFIRMED in the simulator [EMU:tests/test_sim.py, "
        "tests/test_readable.py]. The rpm axis and degrees rest on deltaNE = 180° of crank (LIKELY); "
        "the physical meaning of load is LIKELY.",
    ]
    return "\n".join(md) + "\n", "\n".join(csv) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--write", action="store_true")
    a = ap.parse_args()
    md, csv = build()
    if a.write:
        DOC.write_text(md)
        CSV.parent.mkdir(parents=True, exist_ok=True)
        CSV.write_text(csv)
        print(f"wrote {DOC.relative_to(ROOT)} and {CSV.relative_to(ROOT)}")
    else:
        print(md)
    return 0


if __name__ == "__main__":
    sys.exit(main())
