"""Assemble the 6301 dump programs and generate the reader firmware's header (P3).

    PYTHONPATH=analysis uv run python -m pcmre.romdump          # check the header is current
    PYTHONPATH=analysis uv run python -m pcmre.romdump --write  # regenerate it

Each program becomes one 256-byte page served at $C000-$C0FF. Bytes the program does
not use are SLP ($1A), so a CPU that strays inside the page goes to sleep.
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass

from .roundtrip import ROOT, assemble_asl

SRC = ROOT / "hardware/rp2350-reader/6301"
HEADER = ROOT / "hardware/rp2350-reader/firmware/src/romdump.h"
PAGE = 0xC000
VECTOR = 0xC0C0
FILL = 0x1A  # SLP
PROGRAMS = {"romdump": 0xF000, "romsize": 0xE000}  # name -> first address sent


def assemble(name: str) -> bytes:
    """Return the 256-byte $C0xx page for ``hardware/rp2350-reader/6301/<name>.asm``."""
    src = (SRC / f"{name}.asm").read_text()
    # asl resolves `include` relative to the working directory, so inline it here
    src = src.replace('include "romdump.asm"', (SRC / "romdump.asm").read_text())
    code = assemble_asl(src, VECTOR, VECTOR + 0x3F).rstrip(b"\xff")
    page = bytearray([FILL] * 256)
    page[VECTOR - PAGE : VECTOR - PAGE + len(code)] = code
    return bytes(page)


def header() -> str:
    out = [
        "// Generated by `python -m pcmre.romdump --write` from hardware/rp2350-reader/6301/*.asm.",
        "// Do not edit: tests/test_romdump.py fails if this file is stale.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"#define ROMDUMP_PAGE 0x{PAGE >> 8:02X}u",
        f"#define ROMDUMP_VECTOR 0x{VECTOR:04X}u",
    ]
    for name, start in PROGRAMS.items():
        page = assemble(name)
        out += ["", f"#define {name.upper()}_START 0x{start:04X}u", f"static const uint8_t {name}_page[256] = {{"]
        for i in range(0, 256, 16):
            out.append("    " + ", ".join(f"0x{b:02X}" for b in page[i : i + 16]) + ",")
        out.append("};")
    return "\n".join(out) + "\n"


@dataclass
class Capture:
    mode: int
    start: int
    rom: bytes


def parse_stream(data: bytes, start: int = 0xF000) -> Capture:
    """Split an SCI capture into the mode byte and the ROM image; reject a bad run."""
    want = 1 + 0x10000 - start
    if len(data) != want:
        raise ValueError(f"expected {want} bytes, got {len(data)}")
    mode = data[0] >> 5
    if mode != 0:
        raise ValueError(f"chip latched mode {mode}, not 0: check the P20-P22 straps")
    return Capture(mode, start, data[1:])


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--write", action="store_true")
    a = ap.parse_args()
    text = header()
    if a.write:
        HEADER.parent.mkdir(parents=True, exist_ok=True)
        HEADER.write_text(text)
        print(f"wrote {HEADER.relative_to(ROOT)}")
        return 0
    ok = HEADER.exists() and HEADER.read_text() == text
    print("romdump.h is current" if ok else "romdump.h is STALE: run with --write")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
