; AE86 Bluetop D151801-0642 (cap.bin), HD6301, $F000-$FFFF
; Generated by analysis/pcmre (do not edit by hand; regenerate instead).
; Labels and comments imported from the IDA 4.9 listing; bytes from the ROM.

	cpu	6301
	page	0

; ---- RAM / special function registers (from the listing's RegRAM segment)
Port1DDR	equ	$00
Port2DDR	equ	$01
Port1	equ	$02
Port2	equ	$03
Port3DDR	equ	$04
Port4DDR	equ	$05
Port3	equ	$06
Port4	equ	$07
TmrCntStat1	equ	$08
Timer	equ	$09
OutCmp1	equ	$0B
InpCap1	equ	$0D
Port3CntStat	equ	$0F
UARTRateMode	equ	$10
TxRxCntStat	equ	$11
RxReg	equ	$12
TxReg	equ	$13
RAMCnt	equ	$14
TmrCntStat2	equ	$18
OutCmp2	equ	$1B
InpCap2	equ	$1D
unk_1F	equ	$1F
unk_2D	equ	$2D
unk_32	equ	$32
unk_37	equ	$37
unk_38	equ	$38
unk_3C	equ	$3C
word_40	equ	$40
word_42	equ	$42
word_44	equ	$44
word_46	equ	$46
word_48	equ	$48
byte_4A	equ	$4A
byte_4B	equ	$4B
byte_4C	equ	$4C
byte_4D	equ	$4D
byte_4E	equ	$4E
ADCflags	equ	$4F
ADCRxData	equ	$50
EndTxByteTime	equ	$51
ADCcontrol	equ	$53
ADC_TPS	equ	$54
ADC_12V	equ	$55
ADC_ThA	equ	$56
ADC_ThW	equ	$57
ADC_PWRr	equ	$58
ADC_Oxy	equ	$59
byte_5A	equ	$5A
byte_5B	equ	$5B
byte_5C	equ	$5C
byte_5D	equ	$5D
NextADCsamptime	equ	$5E
byte_5F	equ	$5F
SpdPlsdiff	equ	$60
speedpulses	equ	$61
FullRPM	equ	$62
RPMish	equ	$64
lilRPM	equ	$65
deltaNE	equ	$66
SatCount_68	equ	$68
byte_69	equ	$69
SE056plstime	equ	$6A
SE056Maxtime	equ	$6C
SE056Mintime	equ	$6E
word_70	equ	$70
word_72	equ	$72
FuelRatioH	equ	$74
FuelRatioL	equ	$75
word_76	equ	$76
IC2LowCnt	equ	$78
Inj10OffTime	equ	$79
Inj20OffTime	equ	$7B
InjLoadPulse	equ	$7D
Load	equ	$7F
InjDeadTime	equ	$81
byte_83	equ	$83
byte_84	equ	$84
byte_86	equ	$86
byte_87	equ	$87
byte_88	equ	$88
byte_89	equ	$89
ThAcorr	equ	$8A
byte_8B	equ	$8B
word_8C	equ	$8C
Loadfilt1	equ	$8E
Loadfilt2	equ	$90
byte_92	equ	$92
byte_93	equ	$93
byte_94	equ	$94
byte_95	equ	$95
byte_96	equ	$96
SatCount_97	equ	$97
SatCount_98	equ	$98
TVIScounter	equ	$99
byte_9A	equ	$9A
unk_9B	equ	$9B
SatCount_9C	equ	$9C
byte_9D	equ	$9D
DecelCutRPM	equ	$9E
InCp2TrEg	equ	$9F
AdvanceinUS	equ	$A1
BaseAdvance	equ	$A3
ThW_tADV	equ	$A4
byte_A5	equ	$A5
IDLcompADV	equ	$A6
NEhighWidth	equ	$A7
NEhiDERV_3	equ	$A9
NEhiDERV_2	equ	$AB
NEhiDERV_1	equ	$AD
NEhiDERV	equ	$AF
NEhiwidfilt	equ	$B1
word_B3	equ	$B3
altDwell	equ	$B5
NEtrEdge	equ	$B7
NEleEdge	equ	$B9
Dwell	equ	$BB
word_BD	equ	$BD
word_BF	equ	$BF
IdleRPMfilt	equ	$C1
IdleRPMs	equ	$C3
word_C4	equ	$C4
byte_C6	equ	$C6
SatCount_C7	equ	$C7
byte_C8	equ	$C8
word_C9	equ	$C9
byte_CB	equ	$CB
byte_CC	equ	$CC
unk_CD	equ	$CD
SatCount_CE	equ	$CE
SatCount_CF	equ	$CF
SatCount_D0	equ	$D0
SatCount_D1	equ	$D1
SatCount_D2	equ	$D2
word_D3	equ	$D3
unk_D5	equ	$D5
byte_D6	equ	$D6
byte_D7	equ	$D7
unk_D8	equ	$D8
unk_E6	equ	$E6
unk_FA	equ	$FA
TopStack	equ	$FF

; ---- ROM
	org	$F000

; START	OF FUNCTION CHUNK FOR sub_FD41
reset:
	sei
	sei		; really make it not interrupt.
	lds	#$00FF		; init stackptr
	ldaa	#$C0
	staa	RAMCnt		; enable ram, set ram bit which	gets cleared by	standby	power loss
	ldaa	#$03		; leading edges, but no	interrupts
	staa	TmrCntStat1		; set input edge and output level high,	disable	all interrupts
	staa	TmrCntStat2		; set input edge and output level high,	disable	all interrupts
	std	Timer		; because why not write	to the timer?
	ldd	#$BFFF
	std	Port3		; $port	3 all outputs high except 6, select ADC	- Port4	all bits high
	ldd	#$9FFF
	std	Port1		; port1	bits 7,4,3,2,1 high port 2 all bits high
	ldx	#$6081		; because they're worried they'll wear out accD?
	stx	Port3DDR		; $4 is	direction 3 $5 is direction 4
	ldx	#$EE12
	stx	Port1DDR		; $0 is	direction 1 $1 is direction 2
	jsr	CPUModeTst		; does a mode test and toggles watchdog	pin
	ldx	#$00B4
Clear_RAM:
	clr	$4B,x		; $4b is 75dec,	$b4 is 180dec, so clear	memory starting	from $ff to $4C	inclusive
	dex
	bne	Clear_RAM		; $4b is 75dec,	$b4 is 180dec, so clear	memory starting	from $ff to $4C	inclusive
	ldd	TxRxCntStat		; $11 is txrx control and stat reg, $12	is rxdata reg
	ldaa	#$02		; tx enable, no	interrupts
	staa	TxRxCntStat
	ldx	#$FFAE
initRAMadd:
	inx
	ldab	$00,x		; load ram address to initialize, 0 signals termination	of init	data
	beq	initRAMdone		; FFAF=$4d, so initially doesn't branch, but this is the only way out!
initRAMdata:
	inx
	ldaa	$00,x
	beq	initRAMadd		; run length encoded ram constants are null terminated
	pshx
	ldx	#$0000
	abx		; b contains pointer to	ram value to init with AccA
	staa	$00,x		; init the RAM!
	pulx
	incb		; continue to increment	pointer
	bra	initRAMdata
; ---------------------------------------------------------------------------
initRAMdone:
	ldab	#$10
	cli		; enable interrupts
loc_F051:
	pshb
	jsr	procJmpTable
	pulb
	decb
	bne	loc_F051
	ldab	Timer
	stab	NextADCsamptime		; timer	based
	ldaa	#$1B
	sei
	staa	TmrCntStat1		; timer	control	$1b enables inp	cap int, enables out comp int, rising edge inp trigger,	compare	triggers leading edge.
	staa	TmrCntStat2		; timer	control	$1b enables inp	cap int, enables out comp int, rising edge inp trigger,	compare	triggers leading edge.
Main_Loop:
	lds	#$00FF		; re-init stack	ptr
	ldd	#$EE12
	std	Port1DDR		; re init ddr1 and ddr2
	ldx	#$6081		; re init ddr3 and ddr4
	stx	Port3DDR
	cli
	ldd	byte_4C		; msb inhibits injection
	eorb	Port4		; port 4
	andb	#$40		; '@'      ; p4-6 is SPD input
	beq	loc_F083
	inc	>speedpulses
	eorb	byte_4D		; bit 6	is cache of SPD	pin, flags
	anda	#$FE		; clear	lsb of 4c
	std	byte_4C		; msb inhibits injection
loc_F083:
	ldd	NextADCsamptime		; timer	based
	cmpa	Timer
	bpl	loc_F0FD		; bounce if we already sampled the ADC
	adda	#$10
	incb		; adds 4097
	std	NextADCsamptime		; timer	based
	ldaa	#$DF
	sei
	anda	Port3		; clear	bit5 (mixed signal se056)
	staa	Port3		; clear	bit5 (mixed signal se056)
	cli
	ldd	#$01FE
	andb	ADCcontrol		; clear	bit0
	stab	ADCcontrol		; clear	bit0
	sei
	oraa	ADCflags		; set bit 0
	staa	ADCflags		; set bit 0
	cli
	jsr	loc_FAA7		; force	an adc conversion
	ldaa	byte_5F
	asla
	beq	loc_F0BB
	anda	#$3E
	beq	loc_F0F7
	ldab	byte_4C		; msb inhibits injection
	bitb	#$04
	beq	loc_F0B9
	anda	#$0E
	beq	loc_F0F7
loc_F0B9:
	bra	loc_F0FA
; ---------------------------------------------------------------------------
loc_F0BB:
	ldx	#$FFCF
	jsr	$14,x		; ffe3,	saturate count satcount_CE
	cmpa	#$98
	ldab	byte_4C		; msb inhibits injection
	bitb	#$04
	beq	loc_F0CA
	cmpa	#$04
loc_F0CA:
	bcs	loc_F0D1
	ldaa	#$08
	jsr	flagbadstuf3		; p4-5
loc_F0D1:
	ldd	byte_95		; MSB may be IDL/throttle closed condition
	bpl	loc_F0E8
	incb
	bpl	loc_F0F0
	ldaa	byte_9D
	suba	#$01
	jsr	boundData		; Limits AccA to bounds	set by two bytes after call | Carry	bit is only set	if data	has been clipped at either level |
; ---------------------------------------------------------------------------
	db	$E6
	db	$8F
; ---------------------------------------------------------------------------
	clr	>SatCount_CE
	ldab	#$89
	bra	loc_F0EE
; ---------------------------------------------------------------------------
loc_F0E8:
	decb
	bmi	loc_F0F0
	ldd	#$E634
loc_F0EE:
	staa	byte_9D
; sub_FD41-C58?j
loc_F0F0:
	stab	byte_96
	clrb		; clear	speedpulses when we write D
	ldaa	speedpulses
	std	SpdPlsdiff
; sub_FD41-C8A?j
loc_F0F7:
	jsr	sub_FD41
loc_F0FA:
	jsr	sub_F96A
loc_F0FD:
	ldaa	#$02
	bita	byte_4E		; used for flags in outcmp,inpcap
	beq	loc_F10D
	bsr	comAmask4E
	jsr	sub_F420		; clears IGf bit from port3cntstat
	jsr	BeginCalcADV		; calculates ignition among other things
	bra	end_main
; ---------------------------------------------------------------------------
loc_F10D:
	ldaa	#$01
	bita	byte_4E		; used for flags in outcmp,inpcap
	beq	end_main
	jsr	loc_F534
; sub_FD41-C30?j
end_main:
	jmp	Main_Loop		; re-init stack	ptr
; END OF FUNCTION CHUNK	FOR sub_FD41
; =============== S U B	R O U T	I N E =======================================
; sub_F420+B3?P	...
comAmask4E:
	coma
; End of function comAmask4E
; =============== S U B	R O U T	I N E =======================================
mask4E:
	sei
	anda	byte_4E		; used for flags in outcmp,inpcap
	staa	byte_4E		; could	toggle some bits low
	cli
	rts
; End of function mask4E
; =============== S U B	R O U T	I N E =======================================
ForceInjAccD:
	psha
	ldaa	byte_4D		; lsb inhibits injection here
	rora
	bcc	loc_F12A
tidystkRET:
	ins
locret_F128:
	rts
; End of function ForceInjAccD
; =============== S U B	R O U T	I N E =======================================
ForceInjAccD2:
	psha
loc_F12A:
	ldaa	lilRPM		; 24 = 600 rpm 255 = 6375 RPM
	cmpa	#$8C		; compare to 3500 RPM
	bcc	tidystkRET		; when above 3500 RPM
	pula
loc_F131:
	tsta
	beq	locret_F128
	sei
	bsr	inj1on		; falling through, next	three bytes are	an effective NOP (ldx blahblah)
; End of function ForceInjAccD2
; ---------------------------------------------------------------------------
unk_F137:
	db	$CE
; ---------------------------------------------------------------------------
inj2on:
	std	InCp2TrEg		; probably not just trailing edge
	ldaa	Port1
	rora
	rora
	ldd	Inj20OffTime
	bsr	CalcInjOffTime
	addd	#$001E
	std	Inj20OffTime
	ldd	#$FE0C
	anda	TmrCntStat2		; force	next OC2 low
	staa	TmrCntStat2		; force	next OC2 low
	ldx	Timer
	abx
	stx	OutCmp2		; compare output on P1-1, injector /#20
	rts
; =============== S U B	R O U T	I N E =======================================
; sub_F194?p
; FUNCTION CHUNK AT F191 SIZE 00000003 BYTES
inj1on:
	std	InCp2TrEg		; probably not just trailing edge
	ldaa	Port4		; p4-7 is injector #10
	rola		; injector #10 status in carry bit
	ldd	Inj10OffTime
	bsr	CalcInjOffTime
	subd	#$0000		; seems	unnecessary
	std	Inj10OffTime
	ldaa	#$7F
	anda	Port4		; turn on injector #10
	bra	loc_F191
; End of function inj1on
; =============== S U B	R O U T	I N E =======================================
CalcInjOffTime:
	bcs	loc_F16E		; bounce here if injector off
	subd	Timer
	bpl	loc_F170		; branch if the	offtime	in D is	ahead of the timer
loc_F16E:
	ldd	InjDeadTime		; bounce here if injector off
loc_F170:
	addd	InCp2TrEg		; contains word_7d injection calculation
	bpl	loc_F177
	ldd	#$7FFF		; saturate to 7fff
loc_F177:
	addd	Timer
	rts
; End of function CalcInjOffTime
; =============== S U B	R O U T	I N E =======================================
; injector /#10
; FUNCTION CHUNK AT F196 SIZE 0000001B BYTES
inj1off:
	ldaa	Port4
	bmi	locret_F1B0		; exit if injector #10 is not on
	ldd	Inj10OffTime
	subd	#$0140
	subd	Timer
	bpl	loc_F196		; branch if not	within 320us of	inj off	time
	ldx	Inj10OffTime
loc_F189:
	cpx	Timer
	bpl	loc_F189		; spin waiting for timer
	ldaa	#$80
	oraa	Port4		; turn off injector #10
; End of function inj1off
; START	OF FUNCTION CHUNK FOR inj1on
loc_F191:
	staa	Port4
	rts
; END OF FUNCTION CHUNK	FOR inj1on
; =============== S U B	R O U T	I N E =======================================
; store	d in incp2treg,	turn injector 1	on, get	another	valuve for inj10offtime
sub_F194:
	bsr	inj1on
; End of function sub_F194
; START	OF FUNCTION CHUNK FOR inj1off
loc_F196:
	ldd	#$02FE
	anda	Port1		; test bit 1 (injector #20)
	bne	loc_F1A3		; branch if injector #20 is not	on
	ldx	OutCmp2		; compare output on P1-1, injector /#20
	cpx	Inj10OffTime
	bmi	locret_F1B0		; bomb out if OC2 happens earlier than inj10offtime
loc_F1A3:
	lsra
	andb	TmrCntStat2		; $TCSR2
	aba
	staa	TmrCntStat2		; maintain status quo: next out	cmp will set /#20 to the same value it currently is.
	ldd	Inj10OffTime
	subd	#$00FA
	std	OutCmp2		; compare output on P1-1, injector /#20
locret_F1B0:
	rts
; END OF FUNCTION CHUNK	FOR inj1off
; ---------------------------------------------------------------------------
IRQinpcap:
	ldaa	TmrCntStat1
	bita	TmrCntStat2		; $TCSR2
	bmi	IRQinpcap2		; branch if BOTH input capture flags are set
	tsta
	bra	IRQinpcap3		; branch if only input capture 1, or MSB of $4e	is set
; ---------------------------------------------------------------------------
IRQinpcap2:
	ldaa	byte_4E		; used for flags in outcmp,inpcap
IRQinpcap3:
	bmi	procInCp1		; branch if only input capture 1, or MSB of $4e	is set
	jmp	procInCp2		; input	capture	2 is triggered by edges	from pin 7 of se056, which appears to be /NE clipped @5V levels
; ---------------------------------------------------------------------------
procInCp1:
	ldd	InpCap1		; IC1 is ONLY EVER triggered by	leading	edges on p2-0
	subd	NEleEdge		; set during IC1 low handler
	pshb
	psha
	pulx		; xgdx
	ldaa	byte_4E		; used for flags in outcmp,inpcap
	bpl	endIC1_1		; msb gets flagged based on input capture level
	oraa	#$01
	anda	#$7F
	staa	byte_4E		; set bit 0, clear bit 7
	cli
	inx		; input	capture	time - B9 +1
	cpx	SE056Mintime
	bcc	loc_F1DA		; bounce if greater than or equal to
	ldx	SE056Mintime		; enforce minimum load measurement
loc_F1DA:
	cpx	SE056Maxtime
	bcs	loc_F1E0		; bounce if less than
	ldx	SE056Maxtime		; enforce maximum load measurement
loc_F1E0:
	ldaa	unk_CD		; X is now capped between word_6e (low)	and word_6C (high)
	bita	#$01
	beq	loc_F1F0		; bounce is lsb	of unk_cd is low
	ldx	#$0320		; use this value if MSB	of _CD
	ldaa	byte_95		; bounce if MSb	of byte_95 is high
	bmi	loc_F1F0		; either 800 or	1600 or	if we're lucky: InpCap1 - LastIC2treg
	ldx	#$0640
loc_F1F0:
	stx	SE056plstime		; either 800 or	1600 or	if we're lucky: InpCap1 - LastIC2treg
	ldaa	SatCount_97
	oraa	byte_4C		; msb inhibits injection
	oraa	SatCount_98
	bmi	endIC1_1		; return if satcounts are $80 or greater, or msb of byte_4c is set
	ldaa	FuelRatioL		; fuel ratio low nibble
	psha
	ldd	SE056plstime
	jsr	mulDbyStack		; multiplies unk_75 by word_6a,	returns	only upper 16 bits of result
	pshb
	ldx	#$0000
	ldab	FuelRatioH		; fuel ratio high nibble
	abx
	pulb
	beq	loc_F211		; bounce if x is zero
loc_F20C:
	addd	SE056plstime
	dex
	bne	loc_F20C		; multiply loop
loc_F211:
	tsta
	bpl	loc_F217		; middle 16 bit	result of multiplication of unk_74:unk_75 and word_6a, clipped to $7fff
	ldd	#$7FFF
loc_F217:
	std	InjLoadPulse		; middle 16 bit	result of multiplication of unk_74:unk_75 and word_6a, clipped to $7fff
	sei		; mask interrupts for this section
	ldx	byte_69
	bmi	doublejuice		; bounce if byte_69 has	underflowed
	jsr	loc_F131
	ldaa	byte_69
	bne	endIC1_1		; end of IC1 interrupt
	deca		; decrement byte_69
	staa	byte_69		; decrement byte_69
	ldd	InjLoadPulse
	bra	choose_bank
; ---------------------------------------------------------------------------
doublejuice:
	asld
	bpl	choose_bank		; double word_7d in AccD and cap at 32767
	ldd	#$7FFF
choose_bank:
	psha
	ldaa	IC2LowCnt		; decide which bank to fire from the looks of it
	bita	#$02
	pula		; AccD is either word_7d or double word_7d capped at 32767
	beq	endIC1_2		; turns	off OC2	(turns on injector #20)
	jsr	sub_F194		; turns	on injector #10, also sets up the next oc2 interrupt
endIC1_1:
	rti		; end of IC1 interrupt
; ---------------------------------------------------------------------------
endIC1_2:
	jsr	inj2on		; turns	off OC2	(turns on injector #20)
	rti		; end of IC1 interrupt sometimes
; ---------------------------------------------------------------------------
procInCp2:
	ldaa	TmrCntStat2		; input	capture	2 is triggered by edges	from pin 7 of se056, which appears to be /NE clipped @5V levels
	ldx	InpCap2		; captures from	port 1-0, mixed	signal se056
	bita	#$02		; test IEDG
	beq	InCp2low		; branch if input edge that triggered capture was low
InCp2high:
	stx	NEtrEdge
	ldaa	Port2		; looking at /IGT
	bita	#$02
	beq	IGTisON		; branch if /IGT is low
	ldaa	byte_C6
	bgt	IGTisON		; IGT on
	ldd	#$FA0D
	anda	TmrCntStat1		; disable timer	overflow interrupt, IC1	leading	edge, OC1 low
	staa	TmrCntStat1		; disable timer	overflow interrupt, IC1	leading	edge, OC1 low
	ldx	Timer
	abx
	stx	OutCmp1		; outcmp=timer+0D, which is 13us from now...
IGTisON:
	ldd	OutCmp1		; IGT on
	addd	word_B3
	std	InCp2TrEg		; probably not just trailing edge
	ldaa	AdvanceinUS		; could	word_A1	hold the number	of us to offset	back from 10DBTDC?
	inca
	bmi	loc_F27B		; bounce if word_a1 is unsuitable for next oepration
	ldd	NEtrEdge		; leading edge time of tinp2. corresponds to tr	edge of	NE
	addd	NEhighWidth
	subd	AdvanceinUS		; OC1/igt related
	cmpa	InCp2TrEg		; probably not just trailing edge
	bpl	loc_F279
	ldd	InCp2TrEg		; this value gets stored in outcmp1 if the result in D is significantly	smaller	(256)
loc_F279:
	bsr	OC1HighDtoOC1
loc_F27B:
	ldd	#$FDF3
	anda	TmrCntStat2		; set IC2 trailing edge	interrupt
	staa	TmrCntStat2		; set IC2 trailing edge	interrupt
	andb	byte_4E		; used for flags in outcmp,inpcap
	stab	byte_4E		; set bits 2,3 low
	rti
; =============== S U B	R O U T	I N E =======================================
OC1HighDtoOC1:
	psha
	ldaa	#$19
	oraa	TmrCntStat1		; set oc1 level	high
	staa	TmrCntStat1		; set oc1 level	high
	pula
; End of function OC1HighDtoOC1
; =============== S U B	R O U T	I N E =======================================
; write	d to outcmp
stdOC1:
	std	OutCmp1
	subd	Timer
	cmpa	#$F0		; 240*256=61440us, safety check	i suppose
	bcs	stdOC1Dgood
stdOC1Dnogd:
	ldd	#$000F
	addd	Timer
	std	OutCmp1		; set outcmp to	timer +	F, which is 15us from now
stdOC1Dgood:
	rts
; End of function stdOC1
; ---------------------------------------------------------------------------
forceIGToff:
	ldd	#$0219
	bita	Port2		; test for /IGT
	bne	stdOC1Dgood		; return if /IGT is off
	orab	TmrCntStat1		; set oc1 level	to high
	stab	TmrCntStat1		; set oc1 level	to high
	bra	stdOC1Dnogd		; forces an OC1	shortly
; ---------------------------------------------------------------------------
InCp2low:
	stx	InCp2TrEg		; probably not just trailing edge
	ldaa	byte_4E		; checking bit 3
	bita	#$08
	bne	IC2low3
	ldaa	AdvanceinUS		; OC1/igt related
	bpl	IC2low2+1		; force	IGT off
	ldd	InCp2TrEg		; probably not just trailing edge
	subd	AdvanceinUS		; OC1/igt related
	bsr	OC1HighDtoOC1
IC2low2:
	cpx	#$8DDE		; 8dde is BSR forceIGToff, which jumps to f29F
IC2low3:
	ldd	InCp2TrEg		; probably not just trailing edge
	subd	NEleEdge		; set during IC1 low handler
	std	deltaNE		; =incp2treg-word_b9
	ldab	SatCount_68		; seems	to count main loops between incp2 trailing edges
	clr	>SatCount_68		; reset	satcount_68
	cmpb	#$0D
	bcs	IC2low5		; bounce if satcount_68	was lower than 13, engine spinning fast
	cmpb	#$16
	bhi	IC2low4		; engine spinning slow
	tsta
	bmi	IC2low5		; branch if 916RPM or slower, if we're already here.
IC2low4:
	ldd	#$FFFF		; about	458 RPM
	std	deltaNE		; set to FFFF
IC2low5:
	cmpa	#$EA		; '?'      ; msbyte of delta NE, compare to 204 (which is 59904 - 60159)
	bcc	IC2low6		; branch if 498	RPM or lower
	ldaa	byte_C6
	ldab	byte_4B
	cmpb	#$04
	bcs	IC2low7
IC2low6:
	ldaa	#$05
IC2low7:
	tsta
	bmi	IC2low8
	deca
	staa	byte_C6
IC2low8:
	ldaa	TmrCntStat2		; $TCSR2
	asla
	bpl	IC2low9		; branch if OC2	flag low
	jsr	injector2
	jsr	inj1off		; injector /#10
IC2low9:
	ldd	InCp2TrEg		; probably not just trailing edge
	std	NEleEdge		; =incp2treg
	subd	NEtrEdge		; leading edge time of tinp2. corresponds to tr	edge of	NE
	std	NEhighWidth
	subd	NEhiwidfilt		; d now	contains the derivative	of NEhighwidth
	addd	NEhiDERV_3		; last filtered	NE high	width derivative
	asra		; equivalent to	an arithmetic shift right D (preserves sign of value in	d)
	rorb
	ldx	NEhiDERV_2		; begin	the shuffle of buffles,	this is	a delay	by 4 routine...	for a 4	cylinder motor nonetheless
	stx	NEhiDERV_3		; last word_ab
	ldx	NEhiDERV_1		; last word_af
	stx	NEhiDERV_2		; last word_ad
	ldx	NEhiDERV
	stx	NEhiDERV_1		; last word_af
	tst	>byte_C6
	ble	IC2low10		; avoid	nuking filtered	derivative if unk_c6 <=	zero
	clra
	clrb
IC2low10:
	std	NEhiDERV
	ldd	NEhiwidfilt
	addd	NEhighWidth
	rora
	rorb
	std	NEhiwidfilt
	addd	NEhiDERV_3		; last word_ab
	std	NEhighWidth
	ldd	#$1A1A
	orab	TmrCntStat1		; IC1 edge 1, OC1 unaffected
	stab	TmrCntStat1		; IC1 edge 1, OC1 unaffected
	oraa	TmrCntStat2		; IC2 edge 1, OC2 unaffected
	staa	TmrCntStat2		; IC2 edge 1, OC2 unaffected
	ldab	byte_4E		; used for flags in outcmp,inpcap
	ldaa	IC2LowCnt		; counts input capture 2 trailing edges, reset by p3 msb low (G+ related)
	inca
	staa	IC2LowCnt		; counts input capture 2 trailing edges, reset by p3 msb low (G+ related)
	cmpa	#$03
	bls	IC2low11
	tba
	asla
	oraa	Port3		; inputs to port3 are 7	-G+, 4,3,2,1,0
	bmi	IC2low11		; branch if G+ related is high
	ldaa	#$FE
	anda	Port4		; p4-0 is output to SE056 mixed	signal ic, begin generating 50us low pulse
	staa	Port4		; p4-0 is output to SE056 mixed	signal ic, begin generating 50us low pulse
	clra
	staa	IC2LowCnt		; counts input capture 2 trailing edges, reset by p3 msb low (G+ related)
	staa	SatCount_D1		; clear	unk_d1
	ldaa	ADC_ThW		; compare to 80
	cmpa	#$50
	bls	IC2low11		; branch if less than 80 deg F
	orab	#$20
IC2low11:
	orab	#$46
	ldaa	#$01
	bita	Port2		; looking at mixed signal chip input bit 0, input capture pin
	beq	IC2low12		; branch if IC1	pin is low
	ldaa	TmrCntStat1		; interested in	ICF bit	7
	bpl	IC2low13		; branch if ICF	was not	set
IC2low12:
	orab	#$80
IC2low13:
	stab	byte_4E		; potential to set bits	7,6,5,2,1 high
	ldaa	#$01
	oraa	Port4		; p4-0 is output to SE056 mixed	signal ic, finish 50us low pulse
	staa	Port4		; p4-0 is output to SE056 mixed	signal ic, finish 50us low pulse
	rti
; ---------------------------------------------------------------------------
IRQoutcmp:
	ldaa	TmrCntStat2
	asla
	bmi	procOCmp2		; branch if ocf2 is set	(injector related)
	ldaa	TmrCntStat1
	tab
	comb
	bitb	#$41
	bne	OutCmpBombout		; if bit 6 or 1	was low	in tmrcntstat branch: if we're here for no reason (ocf flag was NOT set??) or we're here because a compare forced /IGT low, branch
	ldab	byte_4E		; test bit 3, if high leave interrupt without doing much
	bitb	#$08
	bne	OutCmpBombout
	orab	#$08
	stab	byte_4E		; set bit 3 high
	ldab	byte_C6		; bail out of interrupt	if >0
	bgt	OutCmpBombout
	anda	#$FA		; '?'      ; a still contains tmrcntstat
	staa	TmrCntStat1		; next compare forces /IGT low (active)
	ldd	OutCmp1		; load last compare time, which	should have initiated this interrupt
	addd	altDwell		; word_b5 contains a duration
	std	word_BD		; word_bd contains alternate leading edge to igniter
	ldd	deltaNE		; outcomp
	subd	altDwell		; ADC_12V*4+384, abs max 1404
	subd	Dwell		; Probably dwell
	bcc	loc_F39F		; this add will	remove altdwell	from the dwell calculation
	clra
	clrb
loc_F39F:
	addd	word_BD		; this add will	remove altdwell	from the dwell calculation
	psha
	ldaa	byte_4E		; used for flags in outcmp,inpcap
	bita	#$04
	pula		; pulls	dont touch cond	codes
	beq	loc_F3AC
	jsr	OutCmp1Sub1		; called from output compare ISR
loc_F3AC:
	jsr	stdOC1		; write	d to outcmp
	rti
; ---------------------------------------------------------------------------
OutCmpBombout:
	oraa	#$01
	staa	TmrCntStat1		; set output high on cmp
	ldd	OutCmp1		; will clear OCF flag
	std	OutCmp1		; Will clear OCF1 flag
	rti		; final	end to output compare interrupt
; =============== S U B	R O U T	I N E =======================================
injector2:
	ldaa	TmrCntStat2		; $TCSR2
	oraa	#$01
	staa	TmrCntStat2		; next OC2 will	set /#20 high
	ldx	Inj20OffTime
	stx	OutCmp2		; compare output on P1-1, injector /#20
	cpx	Timer
	bpl	injector2ret		; terminate if next compare is after current time
	ldd	#$0209		; which	is also	521us
	anda	Port1		; test status of bit 1 (injector #20)
	bne	injector2ret		; terminate if injector	#20 is off
	addd	Timer
	std	OutCmp2		; compare output on P1-1, injector /#20
	bra	injector2
; ---------------------------------------------------------------------------
; injector2+13?j
injector2ret:
	rts
; End of function injector2
; ---------------------------------------------------------------------------
procOCmp2:
	bsr	injector2
	jsr	inj1off		; injector /#10
	rti
; ---------------------------------------------------------------------------
IRQSerial:
	ldd	TxRxCntStat
	bpl	SerBombOut		; branch if bit	15=0, means there's no receive data (why are we interrupting?)
	cli
	anda	#$40		; '@'      ; test for overrun or framing error
	beq	SerIRQMain		; no error
	jsr	txadc3		; error, after re-init the adc gets selected and output	from adcchanselect gets	written	to txreg
SerBombOut:
	rti
; ---------------------------------------------------------------------------
SerIRQMain:
	ldaa	ADCflags		; flag which can be modified in	an interrupt, msb inidicates adc data is pending in adcrxdata
	rora
	ldaa	Port3		; test to see if /CS to	the ADC	is set
	bita	#$40
	bne	SerialDebug		; branch if ADC	was not	selected (to serial debug routine)
	stab	ADCRxData		; b has	rx data
	bcc	SerIRQflag		; branch if lsb	of $4f when loaded was 0
	ldab	ADCcontrol		; controls a jump table	at fa9b, also deselects	ADC with LSB, also controls which channel to select
	rorb
	bcs	SerIRQflag		; branch if ADCcontrol was odd
	oraa	#$40		; '@'      ; here is where to inject serial RMCR edits with JSR $7F00 NOP or whateer
	staa	Port3		; Deselect ADC p3-6 if ADCcontrol was even
SerIRQflag:
	ldab	#$80
	orab	ADCflags		; set bit 7
	stab	ADCflags		; set bit 7
SerMainRet:
	sei		; disable interrupts
	ldd	Timer		; load counter into d
	addd	#$0140		; add 320us, exactly 10	bits (serial byte!) from now
	std	EndTxByteTime		; caches timer values from serial interrupt
	rti
; ---------------------------------------------------------------------------
SerialDebug:
	ldx	#$0000
	abx		; add rx byte to index reg
	ldd	$00,x		; grab byte pointed to by rx byte
	sei
	staa	TxReg		; tx byte pointed to by	rx byte
	ldaa	#$20
txwaitloop1:
	bita	TxRxCntStat		; test if tx reg empty
	beq	txwaitloop1		; tx wait loop
	stab	TxReg
	bra	SerMainRet		; disable interrupts
; =============== S U B	R O U T	I N E =======================================
sub_F420:
	sei
	ldaa	Port3CntStat		; operation clears is3 flag
	ldab	Port3		; operation clears is3 flag
	cli
	clrb
	stab	Port3CntStat		; nuke all special features of port3
	rola		; put /IS3 bit into carry, relace with SEC to remove IGt functionality
	ldd	#$7B79
	bcc	RevLimiter		; carry	bit will be set	from trailing edge on /IS3 pin (IGF)
	staa	SatCount_98		; set unk_98 to	$7B
RevLimiter:
	ldx	deltaNE		; outcomp
	cpx	#$0FD6		; exactly 7400rpm, set to 3750 for 8000	RPM, 3332 for 9003 RPM
	bcs	loc_F43A		; increment unk_97, increment unk_98
	stab	SatCount_97		; set unk_97 to	$79
loc_F43A:
	ldx	#$FF98		; increment unk_97, increment unk_98
	jsr	$49,x		; FFE1,	saturate count satcount_97 and satcount_98
	bpl	CalcRPM		; rts, prior instructions are LSRD
	ldaa	#$02
	jsr	flagbadstuf3		; p4-5
CalcRPM:
	ldx	#$FC81		; rts, prior instructions are LSRD
	ldd	deltaNE		; the next few lines of	code do	SOMETHING with deltaNE,	could calculate	an RPM variable	maybe
CalcRPM2:
	bita	#$F0
	beq	CalcRPMTable		; test if msN is clear
	dex		; decrementing x to point to equivalent	lsrd instructions in DivDby16
	lsrd
	bra	CalcRPM2
; ---------------------------------------------------------------------------
CalcRPMTable:
	pshx
	ldx	#$FEF9
	jsr	$34,x		; ff2d
	jsr	DivDby16
	adda	#$08
	pulx
	jsr	$00,x
	cmpa	#$09
	bls	loc_F468		; table	output,	suitably divided, capped to $9ff (2559d)
	ldd	#$09FF
loc_F468:
	std	word_D3		; table	output,	suitably divided, capped to $9ff (2559d)
	subd	#$0090
	jsr	sub_F5E3		; saturates after 1246 RPM
	stab	IdleRPMs		; precision RPM	counter	for idle control, saturates at 1246 RPM
	clra
	subb	IdleRPMfilt
	sbca	#$00
	asld
	asld
	asld
	addd	IdleRPMfilt
	std	IdleRPMfilt
	ldd	word_C4		; rpm related
	ldx	FullRPM		; full range first dervitive continuous	RPM variable, rpms: 600, 8000 values: 192, 2560
	stx	word_C4		; rpm related
	subd	word_D3		; looks	like a temp variable for subs
	bcc	loc_F48A
	clra
	clrb
loc_F48A:
	jsr	sub_F5E2		; shift	D right	one time, if A then B=FF
	cmpb	#$06
	bcs	loc_F494
	clra
	staa	byte_87
loc_F494:
	stab	unk_D5
	ldd	word_D3		; looks	like a temp variable for subs
	std	FullRPM		; full range first dervitive continuous	RPM variable, rpms: 600, 8000 values: 192, 2560
	lsrd
	lsrd
	lsrd
	std	word_D3		; looks	like a temp variable for subs
	jsr	sub_F5E3		; saturates at 6375 rpm
	stab	lilRPM		; 24 = 600 rpm 255 = 6375 RPM
	ldx	word_D3		; looks	like a temp variable for subs
	ldd	word_D3		; looks	like a temp variable for subs
	cpx	#$00C0		; reduced resolution past 192 (4800 RPM)
	bls	loc_F4B0
	lsrd
	addb	#$60		; absolute max is 255/2	+ 96 = 223
loc_F4B0:
	tba
	suba	#$20
	jsr	boundDataneg		; Limits AccA to bounds	set by two bytes after call
; ---------------------------------------------------------------------------
	db	$D0		; ?		; 208
	db	$00
; ---------------------------------------------------------------------------
	staa	RPMish		; the only place this variable is written
	clra
	staa	SatCount_D0
	ldd	#$0140
	bita	byte_4D		; bit 6	is cache of SPD	pin, flags
	bne	loc_F4DD
	ldaa	lilRPM		; 24 = 600 rpm 255 = 6375 RPM
	jsr	boundData		; Limits AccA to bounds	set by two bytes after call | Carry	bit is only set	if data	has been clipped at either level |
	suba	$14,x		; bounds are CB	(203) and 60 (96) which	are 5075 RPM and 2400 RPM
	bcs	loc_F4E2
	ldaa	Port3
	bpl	loc_F4D6		; branch if G+ related is low
	ldaa	#$40
	jsr	comAmask4E
loc_F4D6:
	ldx	#$FFD2
	jsr	$11,x		; ffe3,	saturate count satcount_d1
	bra	calc56mintime
; ---------------------------------------------------------------------------
loc_F4DD:
	ldaa	#$DF
	jsr	mask4E		; set bit5 low
loc_F4E2:
	sei
	orab	byte_4E		; used for flags in outcmp,inpcap
	stab	byte_4E		; potential to set bit 6 high
	clra
	staa	SatCount_D1		; clear	unk_d1
	cli
calc56mintime:
	ldx	#$00E6
	ldd	#$5002
	cmpa	ADC_ThW		; compare to 80d
	bhi	set56mintime		; branch if over 80 deg	F
	cmpb	SpdPlsdiff
	bhi	set56mintime		; bounce if car	isnt really moving
	ldaa	lilRPM		; 24 = 600 rpm 255 = 6375 RPM
	cmpa	#$50		; 2000 RPM
	bcc	set56mintime		; bounce if higher than	2000 RPM
	cmpa	#$40		; 1600 RPM
	bcc	DecelFuelCut		; bounce if greater than 1600 RPM
	ldx	#$01CC
set56mintime:
	stx	SE056Mintime
DecelFuelCut:
	ldab	DecelCutRPM		; lilRPM related
	ldaa	byte_4C		; msb inhibits injection
	bmi	loc_F510		; zero out bits	6,7 of unk_4c
	addb	#$10		; 400 RPM incremental bump
loc_F510:
	anda	#$3F		; '?'      ; zero out bits 6,7 of unk_4c
	cmpb	lilRPM		; 24 = 600 rpm 255 = 6375 RPM
	bhi	loc_F51E		; bounce if RPM	below cutoff
	ldab	byte_95		; MSB may be IDL/throttle closed condition
	bpl	loc_F51E		; bounce if throttle not closed
	oraa	#$C0		; '?'      ; set bits 7,6 of unk_4c
	bra	Exitsubf420
; ---------------------------------------------------------------------------
loc_F51E:
	ldab	byte_4C		; msb inhibits injection
	bpl	Exitsubf420
	psha		; this code is executed	when unk_4c MSB	is set
	ldaa	unk_D5
	cmpa	#$06
	bhi	loc_F530
	ldd	#$0139
	stab	byte_87
	bsr	loc_F534
loc_F530:
	pula
; sub_F420+100?j
Exitsubf420:
	staa	byte_4C		; msb inhibits injection
	rts
; End of function sub_F420
; ---------------------------------------------------------------------------
; sub_F420+10E?p
loc_F534:
	jsr	comAmask4E
	ldaa	ADC_ThW		; compare to 72d
	cmpa	#$48
	bhi	loc_F542		; branch if over 72 deg	F
	ldaa	#$DF
	jsr	mask4E		; set bit5 low
loc_F542:
	ldd	#$2004
	bita	byte_4E		; test bit 5
	beq	loc_F54E		; can be set to	4, or decremented
	ldab	byte_69
	ble	loc_F550
	decb
loc_F54E:
	stab	byte_69		; can be set to	4, or decremented
loc_F550:
	ldd	SE056plstime
	jsr	Calc72
	std	Load		; roughly equal	to se056 pulse time * air temp table * fuzz factor
	ldaa	byte_4D		; bit 6	is cache of SPD	pin, flags
	rora
	bcc	loc_F571
	ldd	#$0FDC
	cmpb	ADC_ThW		; compare to 220d
	bls	loc_F568		; branch if less than 220 deg F	(ie, not overheating)
	ldx	#$FEB6
	jsr	$65,x		; ff1b
loc_F568:
	std	byte_84
	ldx	#$FEC4
	jsr	$57,x		; ff1b
	std	word_8C
loc_F571:
	ldaa	SatCount_D2
	cmpa	#$02
	bhi	loc_F57F
	bsr	reinitLoads
	ldx	#$FECB
	jsr	$50,x		; ff1b
; ---------------------------------------------------------------------------
	db	$21		; !		; brn
; ---------------------------------------------------------------------------
loc_F57F:
	clra
	staa	byte_86
	ldd	FullRPM		; full range first dervitive continuous	RPM variable, rpms: 600, 8000 values: 192, 2560
	ldx	#$FE9C
	jsr	$91,x		; ff2d
	jsr	DivDby32
	adda	#$08
	std	SE056Maxtime
	ldd	#$0800
	jsr	Calc72		; returns word_72 multiplied by	2 multiplied by	THAcorr
	std	word_72		; air temp compensated
	ldx	#$FED2
	jsr	$49,x		; ff1b
	psha		; this gets multiplied by word_72*2
	jsr	sub_F6E3
	std	word_70		; water	temp compensated
	ldd	#$6666
	cmpb	word_42
	bls	loc_F5AC
	ldaa	#$B3
loc_F5AC:
	cmpa	byte_5D		; =adc_tps - byte_5b, tps related
	bhi	loc_F5BB
	ldd	#$26F0		; b is 6000 RPM
	cmpb	lilRPM		; 24 = 600 rpm 255 = 6375 RPM
	bhi	loc_F5C3		; branch if less than 6000 RPM
	ldaa	#$33
	bra	loc_F5C3
; ---------------------------------------------------------------------------
loc_F5BB:
	ldd	#$19C8
	cmpb	byte_92		; comes	about by load *	lilRPM
	bls	loc_F5C3
	clra
loc_F5C3:
	staa	byte_88
	ldaa	byte_4C		; msb inhibits injection
	bpl	loc_F5EB
	bsr	reinitLoads		; reset	some crap if injection is inhibited
	jmp	loc_F673
; =============== S U B	R O U T	I N E =======================================
reinitLoads:
	ldd	Load		; roughly equal	to se056 pulse time * air temp table * fuzz factor
	std	Loadfilt2
	std	Loadfilt1
	clra
	staa	byte_89		; load related?
	rts
; End of function reinitLoads
; =============== S U B	R O U T	I N E =======================================
sub_F5D8:
	bcs	loc_F5E9
	inx
	subd	#$0080
	bcs	loc_F5E9
; End of function sub_F5D8
; =============== S U B	R O U T	I N E =======================================
; shift	D right	three times, if	A then B=FF
sub_F5E0:
	lsrd
; End of function sub_F5E0
; =============== S U B	R O U T	I N E =======================================
; shift	D right	two times, if A	then B=FF
sub_F5E1:
	lsrd
; End of function sub_F5E1
; =============== S U B	R O U T	I N E =======================================
; shift	D right	one time, if A then B=FF
sub_F5E2:
	lsrd
; End of function sub_F5E2
; =============== S U B	R O U T	I N E =======================================
; If A then B=FF
sub_F5E3:
	tsta
	beq	locret_F5EA
	ldab	#$FF
; ---------------------------------------------------------------------------
	db	$21		; !		; brn
; ---------------------------------------------------------------------------
loc_F5E9:
	clrb
locret_F5EA:
	rts
; ---------------------------------------------------------------------------
loc_F5EB:
	bita	#$04
	bne	loc_F5F6
	ldd	byte_84
	subd	#$0014
	bcc	loc_F5F7		; write	byte_84, byte_85
loc_F5F6:
	clra
loc_F5F7:
	std	byte_84		; write	byte_84, byte_85
	ldab	#$FA
	addb	byte_87
	bcs	loc_F600
	clrb
loc_F600:
	stab	byte_87
	ldd	Loadfilt2
	subd	Load		; roughly equal	to se056 pulse time * air temp table * fuzz factor
	bcs	loc_F61A		; carry	is set when load is increasing
	deca
	bmi	loc_F61A
	bsr	sub_F5E0		; right	shift d	3 times, saturate b if acca is not zero
	ldaa	#$CC
	mul
	ldab	#$B0
	cmpb	ADC_ThW		; water	temp in	farenheit
	bhi	loc_F61A
	ldab	byte_88
	beq	loc_F61B
loc_F61A:
	clra
loc_F61B:
	staa	byte_89		; load related?
	ldd	Loadfilt2
	addd	Load		; roughly equal	to se056 pulse time * air temp table * fuzz factor
	lsrd
	addd	Loadfilt2
	lsrd
	std	Loadfilt2
	ldx	Loadfilt1
	ldd	Load		; roughly equal	to se056 pulse time * air temp table * fuzz factor
	subd	Loadfilt1
	bsr	sub_F5D8		; can increment	x
	pshb
	stx	Loadfilt1
	ldx	#$0006
	ldaa	SpdPlsdiff
	ldab	byte_4C		; msb inhibits injection
	cmpa	#$0F
	bhi	loc_F641		; bounce if vehicle is slower than 15
	andb	#$F7
	bra	loc_F647
; ---------------------------------------------------------------------------
loc_F641:
	cmpa	#$13
	bcs	loc_F649
	orab	#$08
loc_F647:
	stab	byte_4C		; msb inhibits injection
loc_F649:
	bitb	#$08
	bne	loc_F654
	ldaa	ADC_ThW		; water	temp in	farenheit
	cmpa	#$60
	bcc	loc_F654
	dex		; less filtering of load
loc_F654:
	ldd	Load		; roughly equal	to se056 pulse time * air temp table * fuzz factor
loadfiltloop:
	addd	Loadfilt1
	lsrd
	dex		; x can	contain	6 ($f632), or less depending on	previous code
	bne	loadfiltloop
	std	Loadfilt1
	ldd	word_8C
	subd	#$0010
	bcc	loc_F666
	clra
loc_F666:
	std	word_8C
	adda	byte_8B		; tableTHW output (FEBD	decreasing)
	ldab	DecelCutRPM		; lilRPM related
	cmpb	lilRPM		; 24 = 600 rpm 255 = 6375 RPM
	bhi	loc_F671		; branch if RPM	is lower than cutoff
	lsra
loc_F671:
	pulb
	mul
loc_F673:
	tab
	ldaa	byte_4C		; msb inhibits injection
	bita	#$04
	beq	loc_F67B
	clrb
loc_F67B:
	clra
	asld
	asld
	subb	byte_87
	sbca	#$FF
	pshb
	psha
	pulx
	ldab	byte_84
	abx
	abx
	ldab	byte_86
	abx
	abx
	ldd	byte_88
	abx
	tab
	abx
	pshx
	pula
	inca
	staa	word_D3		; looks	like a temp variable for subs
	ldaa	byte_83		; TableTHW output (FEAF	decreasing)
	psha
	bsr	loc_F6E6+1		; DC72 is LDD $72
	addd	word_72
	std	word_72
	bsr	sub_F70A
	lsrd
	lsrd
	std	word_72
	bsr	mulDbyStack		; returns upper	16b in d
loc_F6A8:
	dec	>word_D3		; looks	like a temp variable for subs
	beq	loc_F6B1
	addd	word_72
	bra	loc_F6A8
; ---------------------------------------------------------------------------
loc_F6B1:
	std	word_72
	ldx	#$FF9D
	jsr	$46,x		; ffe3,	saturate count satcount_9c
	jsr	Calc76		; calculates word_76
; End of function sub_F5E3
; =============== S U B	R O U T	I N E =======================================
sub_F6BB:
	ldd	#$0801
	bita	byte_4D		; bit 6	is cache of SPD	pin, flags
	bne	sub_F6D4
	cmpb	SatCount_9C
	ldd	word_72
	bcs	loc_F6D8
	ldab	byte_8B		; tableTHW output (FEBD	decreasing)
	addb	word_8C
	pshb
	bsr	sub_F6E3
	asld
	addd	word_72
	bra	loc_F6D8
; End of function sub_F6BB
; =============== S U B	R O U T	I N E =======================================
sub_F6D4:
	ldaa	word_76		; probably oxygen sensor adjustment, default value is $8000
	bsr	sub_F700		; word_72 multiplied by	msB of word_76 with some shifting returned in d
loc_F6D8:
	subd	word_70		; upper	16 bits	of word_72*2*FED2 coolant temp table
	bcs	loc_F6DE
	clra
	clrb
loc_F6DE:
	addd	word_70		; upper	16 bits	of word_72*2*FED2 coolant temp table
	std	FuelRatioH		; stores the ratio to multiply se056plstime by
	rts
; End of function sub_F6D4
; =============== S U B	R O U T	I N E =======================================
sub_F6E3:
	ldd	word_72
	asld
loc_F6E6:
	cpx	#$DC72		; DC72 is LDD $72
; End of function sub_F6E3
; =============== S U B	R O U T	I N E =======================================
; returns upper	16b in d
mulDbyStack:
	psha
	tsx		; transfer sack	ptr to index register
	ldaa	$03,x		; 0,x is acca, (1/2),x is return vector
	mul		; whats	accb up	to?
	pulb
	psha
	ldaa	$03,x
	mul
	addb	$00,x
	adca	#$00
	ins		; sort of like popping the stack, but without corrupting a register in the process
	pulx
	ins		; gets rid of 8b that was pushed before	sub call
	jmp	$00,x		; like an rts from hell
; End of function mulDbyStack
; =============== S U B	R O U T	I N E =======================================
Calc72:
	std	word_72
	ldaa	ThAcorr
; End of function Calc72
; =============== S U B	R O U T	I N E =======================================
sub_F700:
	psha
	bsr	sub_F6E3		; multiply word_72 by 2	then by	stack, returns upper 16	bits
	addd	word_72
	lsrd
	addd	word_72		; smoothing it with the	last word_72
	lsrd
	rts
; End of function sub_F700
; =============== S U B	R O U T	I N E =======================================
sub_F70A:
	ldaa	lilRPM		; 24 = 600 rpm 255 = 6375 RPM
	ldab	#$CA
	mul
	psha
	ldd	Load		; roughly equal	to se056 pulse time * air temp table * fuzz factor
	bsr	mulDbyStack		; returns upper	16b in d
	jsr	sub_F5E1		; shift	D right	two times, if A	then B=FF
	stab	byte_92		; comes	about by load *	lilRPM
	ldab	word_44
	bpl	loc_F71E
	negb
loc_F71E:
	ldaa	#$08
	mul
	ldx	#$0009
	clc
loc_F725:
	bcs	loc_F72E
	cmpa	byte_92		; comes	about by load *	lilRPM
	bcc	loc_F72E
	clc
	bra	loc_F731
; ---------------------------------------------------------------------------
; sub_F70A+1F?j
loc_F72E:
	suba	byte_92		; comes	about by load *	lilRPM
	sec
loc_F731:
	rolb
	rola
	dex
	bne	loc_F725
	rora
	bcc	loc_F73B
	ldab	#$FF
loc_F73B:
	lsrb
	ldaa	word_44
	bpl	loc_F741
	negb
loc_F741:
	addb	#$80
	tba
	jsr	boundData		; Limits AccA to bounds	set by two bytes after call |
; End of function sub_F70A		; Carry	bit is only set	if data	has been clipped at either level
; ---------------------------------------------------------------------------
	db	$99
	db	$5C
; ---------------------------------------------------------------------------
	adda	word_42
	suba	#$80
	staa	byte_D6
	bra	sub_F700
; =============== S U B	R O U T	I N E =======================================
sub_F751:
	ldaa	word_42
	ldab	word_40
	ldx	byte_95		; MSB may be IDL/throttle closed condition
	bpl	loc_F768
	cba
	rora
	eora	byte_93
	bmi	loc_F766
	ldaa	word_42
	aba
	rora
	aba
	rora
	tab
loc_F766:
	ldaa	word_42
loc_F768:
	pshb
	adda	byte_93
	subb	#$0F
	cba
	bcc	loc_F771
	tba
loc_F771:
	jsr	boundData		; Limits AccA to bounds	set by two bytes after call |
; End of function sub_F751		; Carry	bit is only set	if data	has been clipped at either level
; ---------------------------------------------------------------------------
	db	$B3
	db	$24
; ---------------------------------------------------------------------------
	bcs	loc_F798
	psha
	ldaa	byte_95		; MSB may be IDL/throttle closed condition
	bpl	loc_F797
	ldaa	byte_5C
	jsr	boundData		; Limits AccA to bounds	set by two bytes after call | Carry	bit is only set	if data	has been clipped at either level |
; ---------------------------------------------------------------------------
	db	$8A
	db	$76
; ---------------------------------------------------------------------------
	bcs	loc_F797
	ldaa	word_44
	adda	byte_93
	bvs	loc_F797
	adda	byte_93
	bvs	loc_F797
	tab
	comb
	std	word_44
	inc	>byte_5C
loc_F797:
	pula
loc_F798:
	tab
	comb
	std	word_42
	pula
	tab
	comb
	std	word_40
	rts
; ---------------------------------------------------------------------------
	dw	$1996		; data (f7f1 entry)
	dw	$07AD
	dw	$00EB		; word data
	dw	$004E		; word data
; ---------------------------------------------------------------------------
; START	OF FUNCTION CHUNK FOR Calc76
fake76:
	orab	#$04
	ldaa	#$71
fake76_2:
	staa	unk_9B
fake76_3:
	clr	>SatCount_CE
fake76_4:
	andb	#$F7
	stab	byte_4D		; bit 6	is cache of SPD	pin, flags
	ldd	#$8000
	stab	byte_94		; clear	byte_94
	bra	loc_F811
; END OF FUNCTION CHUNK	FOR Calc76
; =============== S U B	R O U T	I N E =======================================
; FUNCTION CHUNK AT F7AA SIZE 00000014 BYTES
Calc76:
	ldab	byte_4D		; bit 6	is cache of SPD	pin, flags
	bpl	loc_F7C4
	andb	#$FB
loc_F7C4:
	ldx	byte_83		; TableTHW output (FEAF	decreasing)
	bne	fake76
	ldx	byte_87
	bne	fake76_3
	ldaa	byte_4C		; msb inhibits injection
	bmi	fake76_3
	ldaa	SatCount_97
	bmi	fake76_3
	bitb	#$04
	bne	fake76_4
	orab	#$08
	stab	byte_4D		; bit 6	is cache of SPD	pin, flags
	ldd	#$6C6F
	ldx	#$0400
	cpx	Load		; roughly equal	to se056 pulse time * air temp table * fuzz factor
	bhi	loc_F7E7		; bounce
	tba
loc_F7E7:
	ldx	#$FF9C
	jsr	$08,x		; ffa4
	staa	unk_9B
	ldx	#$F7A6		; 235@offset 0,	78 at offset 2
loc_F7F1:
	ldab	Port4
	bitb	#$04		; p4-2 is IDL, active high when	IDL switch is closed
	beq	loc_F7F9		; bounce if not	throttle closed
	inx
	inx		; x would then be F7A8
loc_F7F9:
	ldaa	byte_9A		; oxygen sensor	related
	asla
	ldd	word_76		; probably oxygen sensor adjustment, default value is $8000
	bcc	loc_F802+1		; if msb of unk_9a is low, addd	0,x
	subd	$00,x		; otherwise subtract, is this oxygen sensor feedback control?
loc_F802:
	cpx	#$E300		; e300 is addd 0,x - richen mixture?
	pshb
	ldab	byte_9D		; dynamic limit	to oxy feedback?
	cba
	bcc	capMSB76
	negb
	cba
	bcc	loc_F810
capMSB76:
	tba
loc_F810:
	pulb
loc_F811:
	std	word_76		; probably oxygen sensor adjustment, default value is $8000
	rts
; End of function Calc76
; ---------------------------------------------------------------------------
BeginCalcADV:
	ldd	#$011C		; B contains default timing value, 28/255*90 = 10 degrees
	anda	unk_CD
	bne	No3dtablework		; jump past table lookup because we're in test mode, or other conditions forced -10deg btdc
	ldaa	byte_C6
	bpl	No3dtablework		; jump past table lookup because we're in test mode, or other conditions forced -10deg btdc
	ldaa	byte_95		; msb could signify IDL/throttle closed	condition.
	bpl	Pre3d		; this is the only way we're getting to the 3d table
	ldaa	Port4		; p4-5 is T input to pcm, test mode is active low
	anda	#$20		; ' '      ; p4-5 is T input to pcm, test mode is active low
	bne	IdleADVcomp
No3dtablework:
	jmp	loc_F8EE		; jump past table lookup because we're in test mode, or other conditions forced -10deg btdc
; ---------------------------------------------------------------------------
IdleADVcomp:
	ldaa	IdleRPMfilt
	suba	IdleRPMs		; precision RPM	counter	for idle control, saturates at 1246 RPM
	jsr	boundDataneg		; Limits AccA to bounds	set by two bytes after call
; ---------------------------------------------------------------------------
	db	$10
	db	$00
; ---------------------------------------------------------------------------
	ldab	#$88
	mul
	asld
	asld
	ldab	Port4		; p4-3 is ac input, active high
	andb	#$08		; p4-3 is ac input, active high
	beq	notest2		; bounce if ac is off
	jsr	boundData		; Limits AccA to bounds	set by two bytes after call | Carry	bit is only set	if data	has been clipped at either level |
; ---------------------------------------------------------------------------
	db	$0E
	db	$00
; ---------------------------------------------------------------------------
	ldab	#$0E		; 14 is	about 5	deg advance
notest2:
	staa	IDLcompADV
	ldaa	#$2D
	aba		; b is either 8	from ac	AND check fail,	or 14 from ac code
	clrb
	stab	SatCount_C7		; clear	SatCount_C7
	ldab	word_42
	cmpb	#$42		; 'B'      ; 16896 minimum fr word_42
	bcc	notestexit		; bypasses 3d table lookup
	adda	#$0E		; so from here Acca can	be [45,	59, 73]	which is [16, 21, 26] deg advance
notestexit:
	bra	temploadADV		; bypasses 3d table lookup
; ---------------------------------------------------------------------------
Pre3d:
	clr	>IDLcompADV
	ldx	#$FFC8
	jsr	$1B,x		; ffe3,	saturate count satcount_C7
	cmpa	#$05
	bcc	lookup3dTable		; if SatCount_C7>=5, use the 3d	table
	ldab	#$11
	addb	ThW_tADV
	jmp	SetAdvfromB		; bypass 3d table
; ---------------------------------------------------------------------------
lookup3dTable:
	ldd	Load		; roughly equal	to se056 pulse time * air temp table * fuzz factor
	cmpa	#$0B
	bls	lookup3d2		; now maximum value can	only be	$9FF, this is basically	subtracting 512
	ldd	#$0BFF		; saturate word_7f to $0BFF
lookup3d2:
	suba	#$02		; now maximum value can	only be	$9FF, this is basically	subtracting 512
	bcc	lookup3d3		; bounce if good, otherwise null out
	clra
	clrb
lookup3d3:
	lsrd		; divide by 2, maximum range is	now 4FF
	pshb
	ldab	#$0E		; suggests table size is 14 bytes
	mul		; output can range from	0,E,1c,2a,38
	ldx	#$FF40
	abx
	ldaa	RPMish		; rpms:	[600, 4800, 7200] RPMish value:	[24, 192, 208] - linear	interpolate between points
	pshx
	ldab	#$0E
	abx
	jsr	loc_FF28		; another entry	point
	pulx
	psha
	ldaa	RPMish		; rpms:	[600, 4800, 7200] RPMish value:	[24, 192, 208] - linear	interpolate between points
	jsr	loc_FF28		; another entry	point
	psha
	tsx
	ldd	$01,x
	suba	$00,x
	jsr	sub_FF35		; finish up the	3d table interpolation by calling the final portion of the 2d table interpolate	code
	ins
	pulx
	ldab	TVIScounter		; TVIS counter,	negative (F4) when on, positive	(2) when off, counts back and forth after a transition
	bmi	PWRrAdv		; bounce around	tweaking the output of 3d table	lookup
	adda	#$08		; add 3	deg of base timing if tvis is off
PWRrAdv:
	ldx	#$FF94		; Tweak	output of 3d table with	output of this ADC_PWRr	function, mostly harmless though
	jsr	$10,x		; ffa4
	bcc	temploadADV		; bounce if no carry
	clra
temploadADV:
	staa	BaseAdvance		; stores output	from 3d	lookup
	ldaa	ADC_ThW		; water	temp in	farenheit
	jsr	boundData		; Limits AccA to bounds	set by two bytes after call | Carry	bit is only set	if data	has been clipped at either level |
; ---------------------------------------------------------------------------
	db	$98		; ?		; 152 farenheit
	db	$50		; P		; 80 farenheit
; ---------------------------------------------------------------------------
	bcs	sumallADV+1		; clear	d is bound data	clipped	temp input
	ldx	#$05AA		; only executed	between	80 and 152f
	ldaa	byte_A5		; byte_a5 is only either 0 or D6
	beq	tempload2
	ldx	#$060E
tempload2:
	cpx	Load		; roughly equal	to se056 pulse time * air temp table * fuzz factor
	bcs	sumallADV+1		; clear	d if Load is greater than X
	ldaa	byte_95		; MSB may be IDL/throttle closed condition
	bmi	sumallADV+1		; clear	d if MSB of byte_95
	ldd	#$FFD6
sumallADV:
	cpx	#$4F5F		; clra clrb
	stab	byte_A5		; A:B is either	0:0 or FFD6, 42	counts from 0
	addb	ThW_tADV		; minimum is 28, except	when overheating when it can be	15 (load dependant)
	adca	#$00
	addb	BaseAdvance		; stores output	from 3d	lookup
	adca	#$00
	addb	IDLcompADV
	adca	#$00
	bpl	sumgood		; b is expected	to overflow and	carries	force A	positive
	clra		; force	good sum of 0 advance
	clrb
sumgood:
	jsr	sub_F5E3		; if AccA is 0,	return,	otherwise saturate AccB	to $FF
	tba
	jsr	boundData		; Limits AccA to bounds	set by two bytes after call | Carry	bit is only set	if data	has been clipped at either level |
; ---------------------------------------------------------------------------
	db	$B8		; timing is roughly [this value]/255*90, so 184/255*90=65deg
	db	$1F		; 31, which is 11deg
; ---------------------------------------------------------------------------
	tab
	subb	#$1C		; subtract 10 deg
loc_F8EE:
	stab	unk_D8
SetAdvfromB:
	addb	#$01		; to prevent it	from being 0 I suppose,	incb would save	a byte here
	pshb
	ldd	deltaNE		; outcomp
	jsr	DivDby16
	std	word_D3		; =deltane/16
	ldd	deltaNE		; outcomp
	jsr	mulDbyStack		; returns upper	16b in d
	lsrd
	inca		; add 256us of advance (11.3644	degrees	at 7400	RPM, 0.0074 degrees at idle)
	subd	word_D3		; subtract 11.25 degrees of timing (account for	timing of NE edge at 10	degrees	BTDC)
	bcs	setnforgetADV		; branch if timing was less than 11.25 deg
	subd	NEhighWidth		; which	im assuming is exactly 50% of the NE duty cycle, should	set the	carry
	bcs	loc_F90B
	clra		; set advance to 0 deg
	clrb
loc_F90B:
	addd	NEhighWidth
setnforgetADV:
	std	AdvanceinUS		; word_a1 is the backoff from 10degrees	BTDC to	fire the igniter in us
	ldd	word_D3		; deltane/16
	addd	word_BF		; tops out at 8160 at 8.6V
	std	Dwell		; Probably dwell
	lsrd
	std	word_D3		; looks	like a temp variable for subs
	ldd	deltaNE		; outcomp
	subd	altDwell		; ADC_12V*4+384, abs max 1404
	subd	#$0064
	subd	word_D3		; looks	like a temp variable for subs
	bcs	loc_F925
	clra
	clrb
loc_F925:
	addd	word_D3		; looks	like a temp variable for subs
	std	word_B3
	ldaa	#$01
	ldab	byte_C6
	bmi	loc_F936
	sei
	oraa	TmrCntStat1		; set output compare level to high
	staa	TmrCntStat1		; set output compare level to high
	bra	ExitCalcADV
; ---------------------------------------------------------------------------
loc_F936:
	bsr	OutCmp1Sub1		; called from output compare ISR
	std	word_D3		; looks	like a temp variable for subs
	ldd	#$0C02
	eora	byte_4E		; xor with $0C %00001100
	bita	#$0E
	bne	ExitCalcADV		; branch if bits 2,3 were low or bit 1 was high
	bitb	Port2		; looking at /IGT
	beq	ExitCalcADV		; branch if /IGT low
	ldd	word_D3		; looks	like a temp variable for subs
	std	OutCmp1
	ldx	TmrCntStat1
	jsr	stdOC1		; write	d to outcmp
ExitCalcADV:
	cli
	rts
; =============== S U B	R O U T	I N E =======================================
; called from output compare ISR
OutCmp1Sub1:
	ldd	deltaNE		; outcomp
	subd	AdvanceinUS		; OC1/igt related
	subd	Dwell		; Probably dwell
	bcc	loc_F95C
	clra
	clrb
loc_F95C:
	addd	NEleEdge		; set during IC1 low handler
	sei
	subd	word_BD		; output compare routine only
	cmpa	#$E8
	bcs	loc_F967
	clra
	clrb
loc_F967:
	addd	word_BD		; output compare routine only
	rts
; End of function OutCmp1Sub1
; =============== S U B	R O U T	I N E =======================================
sub_F96A:
	ldx	#$FF69
	jsr	$7A,x		; ffe3,	saturate count satcount_68
	ldd	#$077F
	anda	byte_5F
	andb	Port1		; anding with 7f=0b0111111
	cmpa	byte_D7
	bcs	loc_F97C		; has potential	to toggle bit 7	- /VF ouput generation
	orab	#$80
loc_F97C:
	stab	Port1		; has potential	to toggle bit 7	- /VF ouput generation
	ldaa	ADC_Oxy		; 0.45V
	cmpa	#$17
	ldaa	byte_9A		; oxygen sensor	related
	bcs	oxy_low
	inca
	jsr	boundData		; Limits AccA to bounds	set by two bytes after call | Carry	bit is only set	if data	has been clipped at either level |
; ---------------------------------------------------------------------------
	db	$81
	db	$67
; ---------------------------------------------------------------------------
	bra	loc_F995
; ---------------------------------------------------------------------------
oxy_low:
	deca
	cmpa	unk_9B
	bcc	loc_F995
	ldaa	unk_9B
loc_F995:
	staa	byte_9A		; oxygen sensor	related
	eora	byte_4D		; bit 6	is cache of SPD	pin, flags
	anda	#$80
	beq	loc_F9F7
	eora	byte_4D		; bit 6	is cache of SPD	pin, flags
	staa	byte_4D		; bit 6	is cache of SPD	pin, flags
	bita	#$08
	beq	loc_F9F7
	ldab	#$01
	ldaa	word_76		; probably oxygen sensor adjustment, default value is $8000
	adda	byte_93
	rora		; carry	rotated	into bit 7
	bmi	loc_F9AF
	negb
loc_F9AF:
	stab	byte_93
	ldab	byte_95		; MSB may be IDL/throttle closed condition
	bmi	loc_F9BF
	ldab	byte_5C
	cba
	decb
	bcs	loc_F9BD
	addb	#$02
loc_F9BD:
	stab	byte_5C
loc_F9BF:
	ldd	#$B020
	cmpa	ADC_ThW		; compare water	temp to	176 deg	F
	bhi	loc_F9E2
	ldx	Load		; roughly equal	to se056 pulse time * air temp table * fuzz factor
	cpx	#$0190
	bitb	Port4		; interested in	bit 5 -	test input
	bls	loc_F9E2		; branch if test is pulled low or the carry was	set (word_7f-400)
	ldaa	unk_CD
	bita	#$01
	bne	loc_F9E2
	ldaa	byte_96
	bmi	loc_F9E2
	ldaa	byte_94
	cmpa	#$05
	bcs	loc_F9E5
	jsr	sub_F751
loc_F9E2:
	clra
	staa	byte_94
loc_F9E5:
	inc	>byte_94
	ldaa	word_76		; probably oxygen sensor adjustment, default value is $8000
	staa	byte_93
	ldx	#$F7A2
	jsr	$4F,x		; f7f1 - data product seems to be word_76
	clra
	staa	SatCount_CE		; reset	satcount_ce
	jsr	sub_F6D4		; end product seems to be word_74
loc_F9F7:
	ldaa	byte_95		; MSB may be IDL/throttle closed condition
	ldab	Port4		; p4-2 is IDL input, active low
	andb	#$04
	beq	loc_FA0E		; bounce if throttle closed
	tsta
	bmi	loc_FA05
	clr	>byte_94
loc_FA05:
	ldab	byte_5D		; =adc_tps - byte_5b, tps related
	bmi	loc_FA3B
	inca
	bne	loc_FA39
	bra	loc_FA3B
; ---------------------------------------------------------------------------
loc_FA0E:
	stab	byte_87
	tsta		; AccA is still	byte_95
	bmi	loc_FA19
	cmpa	#$1C
	bcs	loc_FA31
	bra	loc_FA26
; ---------------------------------------------------------------------------
loc_FA19:
	ldaa	lilRPM		; 24 = 600 rpm 255 = 6375 RPM
	cmpa	#$64		; 2500 RPM
	bcc	loc_FA26
	ldd	#$07D0
	jsr	ForceInjAccD
	cli
loc_FA26:
	ldaa	byte_4D		; bit 6	is cache of SPD	pin, flags
	anda	#$01
	bne	loc_FA31
	staa	SatCount_9C
	jsr	sub_F6BB
loc_FA31:
	ldab	byte_4C		; msb inhibits injection
	andb	#$3F		; '?'      ; clear bits 7 and 6
	stab	byte_4C		; clear	bits 7 and 6
	ldaa	#$03
loc_FA39:
	staa	byte_95		; MSB may be IDL/throttle closed condition
loc_FA3B:
	ldd	#$10FE
	anda	Port4		; p4-4 is start	signal
	beq	loc_FA60		; bounce if not	starting
	andb	byte_4C		; msb inhibits injection
	stab	byte_4C		; clear	lsb if starting
	ldaa	byte_4B
	ldab	byte_C6
	bmi	loc_FA62
	inca
	beq	loc_FA75
	staa	byte_4B		; increment unk_4b
	cmpa	#$19
	bcs	loc_FA62		; less than 25
	bhi	loc_FA75		; more than 25
	ldd	#$2328		; exactly 25
	jsr	ForceInjAccD2
	cli
	bra	loc_FA75
; ---------------------------------------------------------------------------
loc_FA60:
	staa	byte_4B
loc_FA62:
	ldab	#$4B
	cmpb	SatCount_68		; seems	to count main loops between incp2 trailing edges
	bcc	loc_FA83
	ldab	#$12
	stab	lilRPM		; write	$12 to unk_65
	tsta
	bne	loc_FA75
	ldaa	#$01
	oraa	byte_4C		; msb inhibits injection
	staa	byte_4C		; msb inhibits injection
loc_FA75:
	ldd	#$0405
	orab	byte_4D		; bit 6	is cache of SPD	pin, flags
	stab	byte_4D		; set bits 2, 0
	staa	byte_C6
	staa	byte_69
	clra
	staa	SatCount_CE
loc_FA83:
	ldaa	byte_C6
	bpl	loc_FA92
	ldd	#$14FE		; a is 500 RPM,	which is almost	rock bottom for	measurement
	cmpa	lilRPM		; 24 = 600 rpm 255 = 6375 RPM
	bhi	loc_FA92
	andb	byte_4D		; bit 6	is cache of SPD	pin, flags
	stab	byte_4D		; clear	bit 0
; sub_F96A+122?j
loc_FA92:
	ldab	byte_4D		; bit 6	is cache of SPD	pin, flags
	bitb	#$01
	beq	procJmpTable
	clr	>SatCount_D2		; clear	if MSB of 4D is	set
; End of function sub_F96A
; =============== S U B	R O U T	I N E =======================================
; sub_F96A+12C?j
procJmpTable:
	ldab	ADCcontrol		; controls a jump table	at fa9b, also deselects	ADC with LSB, also controls which channel to select
	andb	#$06
	ldx	#JumpTable		; jump table 4 vectors
	abx		; x can	only be	$FD39, $FD3B, $FD3D or $FD3F
	ldx	$00,x
	jsr	$00,x		; assuming adccontrol is simply	incrementing, even probability of either subroutine
; End of function procJmpTable
loc_FAA7:
	ldx	#$0024
waitADCdata:
	dex
	beq	TXtoADC		; Transmist adc	channel	selection to ADC
	ldd	ADCflags		; accb contains	adcrxdata
	anda	#$80
	beq	waitADCdata		; loop while msb of adcflags is	low
	coma
	sei
	anda	ADCflags		; flag which can be modified in	an interrupt, msb inidicates adc data is pending in adcrxdata
	staa	ADCflags		; ack the msb by clearing it, and possibly everthing else too.
	cli
	pshb		; adcrxdata on the stack
	bsr	ADCchanSelect
	ldx	#$0054
	abx		; x now	contains $54+0..5
	bsr	TXtoADC		; Transmist adc	channel	selection to ADC
	pulb
	ldaa	#$01
revBitOrder:
	rorb		; push new lsb into carry
	rola		; pull old lsb out of carry
	bcc	revBitOrder		; this loop will reverse the bit order of the value in B and leave the new value in A
	cpx	#$0057
	bne	procThA		; do not jump for $57, jump for	$56
	pshx		; process data from water temp sensor ThW
	ldx	#$FEF0
	jsr	$38,x		; ff28
	bsr	boundData		; Limits AccA to bounds	set by two bytes after call | Carry	bit is only set	if data	has been clipped at either level |
; ---------------------------------------------------------------------------
	db	$F1		; ?		; 241 deg F
	db	$04		; 4 deg	F
; ---------------------------------------------------------------------------
	bcc	loc_FADD		; if the carry was clear the data was not clipped
	ldaa	ADC_ThW		; water	temp in	farenheit
loc_FADD:
	psha
	ldaa	#$04
	jsr	FlagBadStuff		; acca=$04
	pula
	bcc	saveADCdata1
	ldaa	#$C0		; '?'      ; default water temp?
	bra	saveADCdata1
; ---------------------------------------------------------------------------
procThA:
	cpx	#$0056
	bne	saveADCdata2
	pshx		; process data from air	temp sensor ThA
	bsr	boundData		; Limits AccA to bounds	set by two bytes after call | Carry	bit is only set	if data	has been clipped at either level |
; ---------------------------------------------------------------------------
	db	$FA
	db	$06
; ---------------------------------------------------------------------------
	bcc	loc_FAF8
	ldaa	ADC_ThA
loc_FAF8:
	psha
	ldaa	#$40
	jsr	FlagBadStuff		; acca=$40
	pula
	bcc	saveADCdata1
	ldaa	#$79		; 'y'      ; default air temp?
saveADCdata1:
	pulx
saveADCdata2:
	staa	$00,x
	rts
; =============== S U B	R O U T	I N E =======================================
; Transmist adc	channel	selection to ADC
TXtoADC:
	ldaa	Port3
	bita	#$40
	beq	txadc2		; test to see if we're talking to the ADC (p3-6 low)
	pshx
txwaitFB0E:
	ldx	Timer		; load timer
	cpx	EndTxByteTime		; word_51 is 320us greater than	the termination	of the last serial interrupt
	bmi	txwaitFB0E		; loop while time haas not expired yet,	while presumably tx is busy
	pulx
txadc2:
	inc	>ADCcontrol		; controls a jump table	at fa9b, also deselects	ADC with LSB, also controls which channel to select
txadc3:
	bsr	ADCchanSelect		; called here from serial interrupt when receive error was detected
	ldaa	#$0C		; external clock, 62500	baud (not that thats relevant i	guess)
	staa	UARTRateMode
	ldaa	#$1A		; Rx int enable, rx enable, tx enable
	staa	TxRxCntStat
	ldaa	TxRxCntStat		; read from reg	to clear any pending error bits
	ldaa	#$BF		; '?'      ; bit 6 low
	sei
	anda	Port3		; Select ADC
	staa	Port3		; Select ADC
	stab	TxReg		; tx a value based on the value	in ADCcontrol
	cli
	rts
; End of function TXtoADC
; =============== S U B	R O U T	I N E =======================================
ADCchanSelect:
	ldab	ADCcontrol		; controls a jump table	at fa9b, also deselects	ADC with LSB, also controls which channel to select
	lsrb		; lsb into carry bit
	bcs	adchansel2		; branch if lsb	was high
	ldab	#$05		; otherwise return 5
	rts
; ---------------------------------------------------------------------------
adchansel2:
	andb	#$07
	cmpb	#$07
	beq	adchansel3		; if adccontrol	was initially $xF, return 4
	andb	#$03		; if adccontrol	was any	odd number NOT $xF, return values in the range of 0..3
	rts
; ---------------------------------------------------------------------------
adchansel3:
	ldab	#$04		; if adccontrol	was initially $xF, return 4
	rts
; End of function ADCchanSelect
; =============== S U B	R O U T	I N E =======================================
; Limits AccA to bounds	set by two bytes after call
boundDataneg:
	bcc	boundData		; Limits AccA to bounds	set by two bytes after call | Carry	bit is only set	if data	has been clipped at either level |
	clra
; End of function boundDataneg
; =============== S U B	R O U T	I N E =======================================
; Limits AccA to bounds	set by two bytes after call
; Carry	bit is only set	if data	has been clipped at either level
;
; sub_F420+A6?P	...
boundData:
	pulx
	cmpa	$00,x
	bls	boundData2
	ldaa	$00,x
	bra	boundData3
; ---------------------------------------------------------------------------
boundData2:
	cmpa	$01,x
	bcc	boundDataend
	ldaa	$01,x
boundData3:
	sec
boundDataend:
	jmp	$02,x
; End of function boundData
; ---------------------------------------------------------------------------
jmptable2:
	ldaa	ADC_TPS
	bsr	boundData		; Limits AccA to bounds	set by two bytes after call | Carry	bit is only set	if data	has been clipped at either level |
; ---------------------------------------------------------------------------
	db	$FA
	db	$05
; ---------------------------------------------------------------------------
	psha
	ldaa	#$20		; ' '      ; carry is unmolested by ldaa
	jsr	FlagBadStuff		; acca=$20
	pula
	bcc	loc_FB6E
	ldd	#$FF73
	stab	byte_5D		; =adc_tps - byte_5b, tps related
	bra	loc_FBD4
; ---------------------------------------------------------------------------
loc_FB6E:
	ldab	byte_CC		; used for flagging bad	sensors	probably, bits:	6-ThA, 5-TPS, 2-ThW, 0-afm(not from adc)
	bitb	#$20
	bne	loc_FBD2
	ldab	byte_95		; MSB may be IDL/throttle closed condition
	bmi	loc_FB7C
	ldaa	byte_5B		; TPS related
	bra	loc_FB8F
; ---------------------------------------------------------------------------
loc_FB7C:
	adda	byte_5B		; TPS related
	rora
	adda	byte_5B		; TPS related
	rora
	cmpb	#$83
	bhi	loc_FB89
	inc	>byte_5B		; TPS related
loc_FB89:
	ldab	byte_5B		; TPS related
	cba		; a-b
	bcs	loc_FB8F		; select lower
	tba
loc_FB8F:
	bsr	boundData		; Limits AccA to bounds	set by two bytes after call | Carry	bit is only set	if data	has been clipped at either level |
; ---------------------------------------------------------------------------
	db	$29
	db	$05
; ---------------------------------------------------------------------------
	bcc	loc_FB97
	ldaa	#$26
loc_FB97:
	staa	byte_5B		; TPS related
	ldaa	ADC_TPS
	suba	byte_5B		; TPS related
	bcc	loc_FBA0
	clra
loc_FBA0:
	staa	byte_5D		; =adc_tps - byte_5b, tps related
	ldaa	byte_95		; MSB may be IDL/throttle closed condition
	bmi	loc_FBD2
	ldaa	byte_5D		; =adc_tps - byte_5b, tps related
	suba	byte_5A
	bcs	loc_FBD2
	cmpa	#$04
	bcs	loc_FBD2
	bsr	boundDataneg		; Limits AccA to bounds	set by two bytes after call
; ---------------------------------------------------------------------------
	db	$1C
	db	$00
; ---------------------------------------------------------------------------
	ldx	#$FEA7
	clrb
	jsr	$84,x		; ff2b
	ldab	lilRPM		; 24 = 600 rpm 255 = 6375 RPM
	cmpb	#$50		; 2000 RPM
	bcs	loc_FBC1
	lsra
loc_FBC1:
	psha
	ldd	SE056Maxtime
	subd	SE056plstime
	bls	loc_FBD1		; increment the	stack pointer
	jsr	mulDbyStack		; returns upper	16b in d
	asld
	jsr	ForceInjAccD
	cli
; ---------------------------------------------------------------------------
	db	$21		; !		; branch never,	next byte is ignored when falling through
; ---------------------------------------------------------------------------
loc_FBD1:
	ins
loc_FBD2:
	ldaa	byte_5D		; =adc_tps - byte_5b, tps related
loc_FBD4:
	staa	byte_5A
	rts
; ---------------------------------------------------------------------------
jmptable4:
	ldx	#$FEE2
	jsr	$39,x		; ff1b,	table thw, decel fuel cut rpm lookup
	ldab	SatCount_D2
	cmpb	#$4C
	bhi	loc_FBE4		; p4-3 is ac input, active high
	adda	#$10
loc_FBE4:
	ldab	Port4		; p4-3 is ac input, active high
	bitb	#$08
	beq	loc_FBEF
	jsr	boundData		; Limits AccA to bounds	set by two bytes after call | Carry	bit is only set	if data	has been clipped at either level |
; ---------------------------------------------------------------------------
	db	$FF		; 6375 RPM and beyond
	db	$3C		; 1500 RPM
; ---------------------------------------------------------------------------
loc_FBEF:
	staa	DecelCutRPM		; lilRPM related
	ldaa	ADC_ThA
	ldx	#$FED9
	jsr	$4C,x		; ff25
	staa	ThAcorr
	ldx	#$FF0A
	jsr	$11,x		; ff1b
	ldab	ADC_ThW		; water	temp in	farenheit
	subb	#$DA
	bcs	loc_FC1E		; branch if not	overheating
	tba
	jsr	boundData		; Limits AccA to bounds	set by two bytes after call | Carry	bit is only set	if data	has been clipped at either level |
; ---------------------------------------------------------------------------
	db	$0F
	db	$00
; ---------------------------------------------------------------------------
	ldx	#$FF11
	clrb
	jsr	$19,x		; ff2a
	ldab	byte_95		; MSB may be IDL/throttle closed condition
	bmi	loc_FC1C
	ldx	Load		; roughly equal	to se056 pulse time * air temp table * fuzz factor
	cpx	#$09C4
	bcc	loc_FC1E
loc_FC1C:
	ldaa	#$1C
loc_FC1E:
	staa	ThW_tADV
	ldaa	byte_4A
	cmpa	#$5A
	bne	loc_FC33
	ldx	#$000C
loc_FC29:
	dex		; tests	to see if these	bytes match the	initialization conditions set below
	dex
	beq	loc_FC47
	ldd	$3E,x		; first	load is	$48, last load is $40
	aba
	inca
	beq	loc_FC29		; tests	to see if these	bytes match the	initialization conditions set below
loc_FC33:
	ldx	#$807F
	stx	word_42
	stx	word_40
	ldx	#$00FF
	stx	word_46
	stx	word_48
	stx	word_44
	ldaa	#$5A
	staa	byte_4A
loc_FC47:
	ldab	lilRPM		; 24 = 600 rpm 255 = 6375 RPM
	ldaa	Port1		; interested in	 bit 6 /TVIS
	anda	#$BF		; '?'      ; force bit 6 low, /TVIS on
	cmpb	#$9E		; 3950 RPM
	bcs	setTVIS		; branch if less than 3950 RPM to set TVIS ON
	cmpb	#$AE		; 4350 RPM
	bcs	nosetTVIS		; branch if less than 4350 RPM,	no change to TVIS
	oraa	#$40		; '@'      ; tvis off
setTVIS:
	staa	Port1		; has capability to toggle bit 6 - /TVIS
nosetTVIS:
	ldaa	TVIScounter		; TVIS counter,	negative (F4) when on, positive	(2) when off, counts back and forth after a transition
	ldab	Port1		; interested in	bit 6 /TVIS
	aslb
	bmi	loc_FC67		; branch if tvis off
	deca		; decrement if tvis on
	bpl	storeTVIScntr
	ldaa	#$F4
	bra	storeTVIScntr
; ---------------------------------------------------------------------------
loc_FC67:
	inca		; increment if tvis off
	bmi	storeTVIScntr
	ldaa	#$02
storeTVIScntr:
	staa	TVIScounter		; TVIS counter,	negative (F4) when on, positive	(2) when off, counts back and forth after a transition
; =============== S U B	R O U T	I N E =======================================
; sub_FD41:loc_FE48?P ...
CPUModeTst:
	ldd	#$E004
	anda	Port2		; interested in	mode bits
	cmpa	#$E0
	bne	locret_FC7B		; branch if not	mode7 =	internal
	eorb	Port1		; toggle the watchdog
	stab	Port1		; toggle watchdog bit 2
locret_FC7B:
	rts
; End of function CPUModeTst
; =============== S U B	R O U T	I N E =======================================
DivDby32:
	lsrd
; End of function DivDby32
; =============== S U B	R O U T	I N E =======================================
DivDby16:
	lsrd
	lsrd
	lsrd
	lsrd
	rts
; End of function DivDby16
; ---------------------------------------------------------------------------
jmptable3:
	ldaa	Port3		; test level of	bit4 (input from mixed signal se056)
	anda	#$10
	suba	#$10		; bit4 status is hidden	in carry
	ldaa	#$01
	jsr	FlagBadStuff		; acca=$01
	ldaa	ADC_12V		; +B1 terminal divided by 5... =255*12/25
	suba	#$53		; about	8.1V
	bcc	loc_FC94
	clra
loc_FC94:
	ldx	#$FEE9
	jsr	$3C,x		; ff25
	bsr	DivDby32
	addd	#$01D0
	std	InjDeadTime		; max value is 2504, table output of ADC_12V
	ldaa	ADC_12V		; +B1 terminal divided by 5... =255*12/25
	ldx	#$FF12
	jsr	$13,x		; ff25
	lsrd
	lsrd
	lsrd
	addd	word_BF		; tops out at 8160 at 8.6V
	lsrd
	std	word_BF		; tops out at 8160 at 8.6V
	ldab	ADC_12V		; +B1 terminal divided by 5... =255*12/25
	clra
	asld
	asld
	addd	#$0180
	std	altDwell		; ADC_12V*4+384, abs max 1404
	bra	loc_FCD6
; ---------------------------------------------------------------------------
jmptable1:
	ldaa	byte_95		; MSB may be IDL/throttle closed condition
	bpl	loc_FCC9
	ldab	word_42
	cmpb	#$42
	bcc	loc_FCC9
	ldaa	Port1		; interested in	bit 5, output to port buffer
	bra	loc_FCD2		; bit 5	($20) goes to port buffer, is output
; ---------------------------------------------------------------------------
loc_FCC9:
	ldd	#$DF4C
	anda	Port1		; Zero-ing bit 5
	cmpb	SatCount_D2		; 76-satcount_d2
	bcs	loc_FCD4		; buffer off
loc_FCD2:
	oraa	#$20		; ' '      ; bit 5 ($20) goes to port buffer, is output
loc_FCD4:
	staa	Port1		; can set or clear bit 5 (buffer)
loc_FCD6:
	ldx	#$FFD0
	jsr	$11,x		; FFE1,	saturate count satcount_CF and satcount_D0
	ldab	Port4		; P4-4,	STA input to pcm, high when starting
	bitb	#$10		; test P4-4, STA input to pcm, high when starting i think
	bne	loc_FCEE
	ldab	SatCount_CF
	clr	>SatCount_CF
	cmpb	#$F3
	bcs	loc_FCEE
	cmpa	#$F3
	bcc	loc_FCFE
loc_FCEE:
	cmpa	#$25
	bcs	loc_FCF8
	ldaa	lilRPM		; 24 = 600 rpm 255 = 6375 RPM
	cmpa	#$28		; 1000 RPM
	bcc	loc_FCFE
loc_FCF8:
	ldab	SatCount_D1
	cmpb	#$09
	bcs	flagbadstuf5
loc_FCFE:
	ldaa	#$10
	bra	flagbadstuf3		; p4-5
; =============== S U B	R O U T	I N E =======================================
; FUNCTION CHUNK AT FD2D SIZE 0000000C BYTES
FlagBadStuff:
	bcc	flagbadstuf6
	bita	byte_CC		; used for flagging bad	sensors	probably, bits:	6-ThA, 5-TPS, 2-ThW, 0-afm(not from adc)
	bne	flagbadstuf2
	oraa	byte_CC		; used for flagging bad	sensors	probably, bits:	6-ThA, 5-TPS, 2-ThW, 0-afm(not from adc)
	bra	flagbadstuf7
; ---------------------------------------------------------------------------
flagbadstuf2:
	sec
	bita	#$1F
	beq	flagbadstuf4
; End of function FlagBadStuff
; =============== S U B	R O U T	I N E =======================================
; p4-5
; sub_F420+23?P	...
flagbadstuf3:
	ldab	Port4
	bitb	#$20		; ' '      ; p4-5 is Test mode input. low is check mode
	beq	flagbadstuf4
	ldab	#$DA
	stab	byte_C8
; flagbadstuf3+4?j
flagbadstuf4:
	tab
	orab	unk_CD
	stab	unk_CD
	ldab	Port4		; p4-4 is STA input, active high
	bitb	#$10
	bne	flagbadstuf5		; bomb out if STA starting
	oraa	word_48
	tab
	comb
	std	word_48
; flagbadstuf3+13?j
flagbadstuf5:
	rts
; End of function flagbadstuf3
; ---------------------------------------------------------------------------
; START	OF FUNCTION CHUNK FOR FlagBadStuff
flagbadstuf6:
	coma
	tab
	andb	unk_CD
	stab	unk_CD
	anda	byte_CC		; used for flagging bad	sensors	probably, bits:	6-ThA, 5-TPS, 2-ThW, 0-afm(not from adc)
flagbadstuf7:
	staa	byte_CC		; used for flagging bad	sensors	probably, bits:	6-ThA, 5-TPS, 2-ThW, 0-afm(not from adc)
	clc
	rts
; END OF FUNCTION CHUNK	FOR FlagBadStuff
; ---------------------------------------------------------------------------
JumpTable:
	dw	jmptable1		; DATA XREF: procJmpTable+4?o | jump table 4 vectors
	dw	jmptable2
	dw	jmptable3		; test level of	bit4 (input from mixed signal se056)
	dw	jmptable4
; =============== S U B	R O U T	I N E =======================================
; FUNCTION CHUNK AT F000 SIZE 00000119 BYTES
sub_FD41:
	ldx	#$FEAF
	jsr	$6C,x		; ff1b
	staa	byte_83		; TableTHW output (FEAF	decreasing)
	ldx	#$FEBD
	jsr	$5E,x		; ff1b
	staa	byte_8B		; tableTHW output (FEBD	decreasing)
	ldd	#$B020
	cmpa	ADC_ThW		; compare against 176
	bhi	loc_FD5A
	cmpb	byte_92		; comes	about by load *	lilRPM
	bls	loc_FD5D
loc_FD5A:
	clr	>SatCount_CE
loc_FD5D:
	ldx	#$FFD3
	jsr	$10,x		; ffe3,	saturate count satcount_D2
	ldaa	SpdPlsdiff
	bne	loc_FD79		; p4-5,	test input active low
	ldd	#$2001		; a contains 800 RPM
	cmpa	lilRPM		; 24 = 600 rpm 255 = 6375 RPM
	bhi	loc_FD79		; p4-5,	test input active low
	ldaa	byte_C6
	bpl	loc_FD79		; p4-5,	test input active low
	andb	byte_4C		; msb inhibits injection
	orab	word_46
	tba
	comb
	std	word_46
loc_FD79:
	ldab	Port4		; p4-5,	test input active low
	andb	#$20
	beq	loc_FDAE
	ldab	byte_4D		; bit 6	is cache of SPD	pin, flags
	andb	#$08
	beq	loc_FD9D
	ldaa	word_76		; probably oxygen sensor adjustment, default value is $8000
	adda	byte_D6
	rora
	ldab	#$04
	cmpa	#$99
	sbcb	#$00
	cmpa	#$87
	sbcb	#$00
	cmpa	#$79
	sbcb	#$00
	cmpa	#$67
	sbcb	#$00
	aslb
loc_FD9D:
	stab	byte_D7
	clra
	clrb
	std	word_C9
	coma
	staa	byte_CB
	ldab	byte_4D		; bit 6	is cache of SPD	pin, flags
	bitb	#$01
	bne	loc_FE1B		; may set bit 3	- MIL
	bra	loc_FDCE
; ---------------------------------------------------------------------------
loc_FDAE:
	ldaa	byte_95		; MSB may be IDL/throttle closed condition
	bmi	loc_FDB8		; p4-2 is IDL, p4-3 is AC, so idling and ac perhaps?
	ldaa	byte_9A		; oxygen sensor	related
	bpl	loc_FDC6
	bra	loc_FDC4
; ---------------------------------------------------------------------------
loc_FDB8:
	ldaa	Port4		; p4-2 is IDL, p4-3 is AC, so idling and ac perhaps?
	eora	#$04
	anda	#$0C
	oraa	word_46
	oraa	word_48
	bne	loc_FDC6
loc_FDC4:
	ldab	#$08
loc_FDC6:
	stab	byte_D7
	ldab	byte_CB
	addb	#$01
	beq	loc_FE00
loc_FDCE:
	ldaa	byte_C8
	inca
	bne	loc_FE0B
	bcs	loc_FE19
	subb	#$11
	bcc	loc_FE01
	ldd	word_C9
	bne	loc_FDF3
	staa	byte_CB
	ldaa	word_46
	anda	#$01
	ldab	Port4		; another IDL+AC test
	eorb	#$04
	bitb	#$0C
	beq	loc_FDED
	oraa	#$02
loc_FDED:
	ldab	word_48
	std	word_C9
	beq	loc_FE11
loc_FDF3:
	inc	>byte_CB
	lsrd
	bcc	loc_FDF3
	std	word_C9
	ldaa	#$11
	ldab	byte_CB
	mul
loc_FE00:
	clc
loc_FE01:
	stab	byte_CB
	bcs	loc_FE09
	bitb	#$F0
	beq	loc_FE11
loc_FE09:
	ldaa	#$7C
loc_FE0B:
	bvc	loc_FE19
	ldaa	#$FC
	bcc	loc_FE19
loc_FE11:
	ldaa	#$6D
	ldx	word_C9
	bne	loc_FE19
	ldaa	#$5E
; sub_FD41:loc_FE0B?j ...
loc_FE19:
	staa	byte_C8
loc_FE1B:
	ldab	Port1		; may set bit 3	- MIL
	andb	#$F7
	tsta
	bpl	loc_FE24		; toggle MIL
	orab	#$08
loc_FE24:
	stab	Port1		; toggle MIL
	ldab	Port4		; p4-5,	test mode, active low
	bitb	#$20
	beq	loc_FE33
	ldaa	byte_4C		; msb inhibits injection
	anda	#$FB
loc_FE30:
	staa	byte_4C		; msb inhibits injection
locret_FE32:
	rts
; ---------------------------------------------------------------------------
loc_FE33:
	ldaa	byte_95		; MSB may be IDL/throttle closed condition
	anda	byte_5D		; =adc_tps - byte_5b, tps related
	bpl	locret_FE32
	bitb	#$10
	bne	loc_FE43
	ldaa	byte_4C		; msb inhibits injection
	oraa	#$04
	bra	loc_FE30
; ---------------------------------------------------------------------------
loc_FE43:
	ldab	#$C0
	sei
	stab	Port1		; /#20 low, watchdog low, MIL low, bit5	low, /TVIS high	/VF high
loc_FE48:
	jsr	CPUModeTst
	clra
	clrb
	ldx	#$F000
ChkSumLoop:
	addd	$00,x
	inx
	inx
	bne	ChkSumLoop		; loop until x overflows
	subd	#$AA55		; Checksum is forced to	this value by value at FFEE
	beq	nukeram1		; branch if checksum equals aa55
	ldaa	#$C8
	bra	loc_FE8B		; /VF high,/TVIS can toggle, VISC low, MIL high, watchdog low, /#20 low
; ---------------------------------------------------------------------------
nukeram1:
	jsr	CPUModeTst
	ldd	#$55AA
nukeram2:
	ldx	#$00C0
nukeram3:
	std	$3E,x		; this loop nukes all of user ram with alternating 55s and AAs
	dex
	dex
	bne	nukeram3		; this loop nukes all of user ram with alternating 55s and AAs
testram:
	inx
	cmpa	$3F,x
	bne	loc_FE89		; watchdog and /VF
	inx
	cmpb	$3F,x
	bne	loc_FE89		; watchdog and /VF
	cpx	#$00C0
	bne	testram
	comb
	coma
	bmi	nukeram2
	ldaa	Port4		; p4-5,	test mode, active low
	anda	#$20
	beq	loc_FE48
	bra	loc_FE99
; ---------------------------------------------------------------------------
; sub_FD41+135?j
loc_FE89:
	ldaa	#$48		; watchdog and /VF
loc_FE8B:
	staa	Port1		; /VF high,/TVIS can toggle, VISC low, MIL high, watchdog low, /#20 low
; sub_FD41+156?j
loc_FE8D:
	decb
	bne	loc_FE8D
	jsr	CPUModeTst
	ldaa	Port4		; p4-5,	test mode, active low
	anda	#$20
	beq	loc_FE8D
loc_FE99:
	jmp	reset
; End of function sub_FD41
; ---------------------------------------------------------------------------
	db	$1F		; SE056	max pulse time as a function of	FULLRPM	data (ff2d entry)
	db	$1F
	db	$23
	db	$3E
	db	$3E
	db	$57
	db	$64
	db	$64
	db	$68
	db	$5C
	db	$4F
	db	$00		; data (ff2b entry)
	db	$23
	db	$57
	db	$80
	db	$A8
	db	$C2
	db	$D9
	db	$E6
	db	$F3		; ?		; data (ff1b entry)
	db	$80
	db	$45
	db	$1E
	db	$00
	db	$00
	db	$00
	db	$98		; ?		; data (ff1b entry)
	db	$53
	db	$28
	db	$19
	db	$0F
	db	$06
	db	$06
	db	$66		; f		; data (ff1b entry)
	db	$58
	db	$47
	db	$2E
	db	$17
	db	$08
	db	$00
	db	$6C		; l		; data (ff1b entry)
	db	$57
	db	$45
	db	$33
	db	$23
	db	$11
	db	$00
	db	$F3		; ?		; data (ff1b entry)
	db	$80
	db	$1E
	db	$05
	db	$00
	db	$00
	db	$00
	db	$FF		; data (ff1b entry - tableTHW),	used for fuel pulse scaling, 0 deg F
	db	$D8		; ?		; 32 deg F
	db	$90		; ?		; 64 deg F
	db	$68		; h		; 96 deg F
	db	$49		; I		; 128 deg F
	db	$43		; C		; 160 deg F
	db	$40		; @		; 192 deg F
	db	$66		; f		; used for adjusting ADC_THA to	THAcorr
	db	$66
	db	$6A
	db	$77
	db	$83
	db	$8C
	db	$99
	db	$AA
	db	$B9		; ?		; 8
	db	$6C		; l		; Decel	fuel cut compare values	for lilRPM data	(ff1b entry)
	db	$6C		; l		; 2700 RPM
	db	$68		; h		; 2600 RPM
	db	$60		; `		; 2400 RPM
	db	$50		; P		; 2000 RPM
	db	$40		; @		; 1600 RPM
	db	$30		; 0		; 1200 RPM
	db	$FF		; data (ff25 entry), offset by -83d (-8.13V) for ADC_12V
	db	$C2
	db	$4B
	db	$18
	db	$00
	db	$00
	db	$00
	db	$FF		; data for converting raw ThW measurement from ADC (ff28 entry)
	db	$DC
	db	$B2
	db	$9B
	db	$8A
	db	$7C
	db	$70
	db	$66
	db	$5D		; ]		; 8
	db	$53		; S		; data (ff2d entry)
	db	$49
	db	$40
	db	$36
	db	$2A
	db	$1D
	db	$0A
	db	$00
	db	$A5
	db	$84
	db	$6A
	db	$55
	db	$43
	db	$34
	db	$27
	db	$1C		; 15
	db	$13
	db	$38		; data (ff1b entry), additional	timing advance based on	water temp (value/255*90)
	db	$38		; 20 deg
	db	$37
	db	$32
	db	$2D
	db	$1C		; 10 deg
	db	$1C
	db	$1C		; data (ff2a entry)
	db	$06		; data (ff25 entry) for	ADC_12V
	db	$06
	db	$FF
	db	$FF
	db	$D8
	db	$96
	db	$77
	db	$5E
	db	$51
; ---------------------------------------------------------------------------
TableThW:
	ldaa	ADC_ThW
	clrb
	cmpa	#$C0		; 192 deg F
	bls	Tab1		; should be blt, avoid interpolation in	the case of adc_thw==192, and out of bounds memory access
	ldaa	$06,x		; if ADC_ThW>192 automatically load the	last value of all ff1b entry tables and	return
	rts
; ---------------------------------------------------------------------------
Table12V:
	clrb
Tab1:
	lsrd		; next instruction is like a 2 byte nop
; ---------------------------------------------------------------------------
	db	$21		; !		; brn, skips the clrb if e fall	through	this line
; ---------------------------------------------------------------------------
loc_FF28:
	clrb		; another entry	point
	lsrd		; next executed	instruction after ff26 entry
	lsrd
	lsrd
	lsrd		; tablethw, table12v: shifted right 5 times, ff28 shifted right	4 times
	pshb		; lower	nibble of what was initially in	a gets pushed, or another entry	point and push b
	tab
	abx
	ldaa	$01,x		; for tablethw b=0..6, table12v	b=0..7,	ff28 b=0..15
	suba	$00,x		; a now	contains the difference	between	the two	table points
	pulb		; b now	has the	remainder of what was rotated from A
; =============== S U B	R O U T	I N E =======================================
; if table(n+1)-table(n) is positive, we dont need to fart around
sub_FF35:
	bcc	loc_FF3C		; A has	table(n+1)-table(n), b has remainder of	what was used to get table(n)
	nega
	negb
	beq	loc_FF3C		; A has	table(n+1)-table(n), b has remainder of	what was used to get table(n)
	inx
loc_FF3C:
	mul		; A has	table(n+1)-table(n), b has remainder of	what was used to get table(n)
	adda	$00,x		; after mul A contains	offset from table(n)
	rts		; returns data from tables in AccA
; End of function sub_FF35
; ---------------------------------------------------------------------------
	db	$58		; X		; 3d table, x input is byte_64,	y input	is processed word_7f
	db	$63
	db	$71
	db	$7E
	db	$8A
	db	$96
	db	$96
	db	$97
	db	$97
	db	$8F
	db	$8E
	db	$8F
	db	$8D
	db	$8F
	db	$44		; D		; new table 1
	db	$59
	db	$66
	db	$72
	db	$7E
	db	$7E
	db	$7E
	db	$7F
	db	$7F
	db	$77
	db	$76
	db	$72
	db	$71
	db	$72
	db	$21		; !		; new table 2
	db	$3E
	db	$53
	db	$57
	db	$5C
	db	$5D
	db	$5E
	db	$5D
	db	$5D
	db	$61
	db	$62
	db	$62
	db	$63
	db	$64
	db	$13		; possible new table for f880 3
	db	$1D
	db	$28
	db	$35
	db	$3B
	db	$43
	db	$46
	db	$47
	db	$47
	db	$56
	db	$5B
	db	$5B
	db	$5C
	db	$5D
	db	$0B		; new table 4
	db	$10
	db	$13
	db	$22
	db	$27
	db	$28
	db	$2B
	db	$34
	db	$36
	db	$48
	db	$54
	db	$56
	db	$55
	db	$56
	db	$0B		; new table 5
	db	$10
	db	$13
	db	$22
	db	$27
	db	$28
	db	$2B
	db	$2E
	db	$2E
	db	$39
	db	$49
	db	$4E
	db	$55
	db	$56		; V		; end 3d table
	db	$00		; data (ffa4 entry)
	db	$00
	db	$00
	db	$0B
	db	$05		; data (ffe1 entry)
	db	$05
	db	$05
	db	$00
	db	$07		; data (ffa4 entry)
	db	$00
	db	$FB
	db	$00
	db	$00
	db	$07
	db	$FB
	db	$FE
; ---------------------------------------------------------------------------
loc_FFA4:
	ldab	ADC_PWRr
	lsrb
	lsrb
	lsrb
	lsrb
	lsrb		; div by 32, only bits 2..0 can	be 1
	abx		; the range of accb is 0..7
	suba	$00,x
	rts
; ---------------------------------------------------------------------------
	db	$4D		; M		; Data used to initialize RAM (address,	data0,data1,...dataN,$00)
	db	$05		; word data for	4d = $0543
	db	$43
	db	$00
	db	$5B		; [		; new address
	db	$26		; &		; data for word	5b = $2680
	db	$80
	db	$00		; stop RLE
	db	$54		; T		; new address
	db	$73		; s		; $54 =	73
	db	$B3		; ?		; $55 =	B3
	db	$79		; y		; 56
	db	$C0		; ?		; 57
	db	$20		; 58
	db	$00		; stop RLE
	db	$65		; e		; new address
	db	$12		; 65
	db	$FF		; 66
	db	$FF		; 67
	db	$10		; 68
	db	$04		; 69
	db	$02		; 6a
	db	$8A		; ?		; 6b
	dw	$1194		; 6c
	dw	$01CC		; 6e
	db	$7F		; ?		; 70
	db	$FF		; 71
	db	$02		; 72
	db	$01		; 73
	db	$02		; 74
	db	$00		; stop RLE
	db	$95		; ?		; new address
	db	$60		; `		; 95
	db	$34		; 4		; 96
	db	$7A		; z		; 97
	db	$7C		; |		; 98
	db	$F4		; ?		; 99
	db	$71		; q		; 9a
	db	$71		; q		; 9b
	db	$FF		; 9c
	db	$E6		; ?		; 9d
	db	$00		; stop RLE
	db	$C6		; ?		; new address
	db	$04		; c6
	db	$FF		; c7
	db	$5E		; ^		; c8
	db	$00		; termination of init data
	db	$00
; ---------------------------------------------------------------------------
loc_FFE1:
	bsr	loc_FFE3
loc_FFE3:
	ldaa	$FF,x
	inca
	beq	loc_FFEA
	inc	$FF,x
loc_FFEA:
	inx
	ldaa	$FE,x
	rts
; ---------------------------------------------------------------------------
	dw	$C7BE		; illegal opcode trap vector is	used to	force ROM checksum to equal AA55
	dw	IRQSerial		; serial interrupt rdrf	/ orfe / tore
	dw	reset		; timer	overflow
	dw	IRQoutcmp		; timer	output compare
	dw	IRQinpcap		; timer	input capture from mixed signal	SE056
	dw	reset		; /irq or /S3
	dw	reset		; swi
	dw	reset		; /NMI
	dw	reset		; reset	entry vector

	end
